# -*- coding: utf-8 -*-
"""ETL_Shopee_into_py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iPvWzSjnZ2eha7uvw2977CeJgk3iMsMz
"""

import pandas as pd
import numpy as np
import ast
import os
from datetime import datetime
import pytz
import re
import mysql.connector
import random

import io
df_category = pd.read_csv('D:\Final project program\Code\Python\shops.csv')
df_shop = pd.read_csv('D:\Final project program\Code\Python\shop_details.csv')
df_shop_category = pd.read_csv('D:\Final project program\Code\Python\shop_categories.csv')
df_product = pd.read_csv('D:\Final project program\Code\Python\shop_products.csv', low_memory=False)

'''df_category = pd.read_csv('D:\Final project program\Data\shops.csv') 
df_shop = pd.read_csv('D:\Final project program\Data\shop_details.csv') 
df_shop_category = pd.read_csv('D:\Final project program\Data\shop_categories.csv') 
df_product = pd.read_csv('D:\Final project program\Data\shop_products.csv', low_memory=False) '''

df_category = df_category[['category_id',	'category_name', 'shopid']]

"""**Kiểm tra trùng lặp**"""

dup_category_count = df_category.duplicated().sum()
dup_shop_count = df_shop.duplicated().sum()
dup_shop_category_count = df_shop_category.duplicated().sum()
dup_product_count = df_product.duplicated().sum()

print(dup_category_count, dup_shop_count, dup_shop_category_count, dup_product_count)

"""**1. Category**"""

df_category

df_category = df_category.drop_duplicates()

try:
    # Tạo đối tượng connection
    myconn = mysql.connector.connect(host="localhost", user="root", passwd="Thuy281001", database="shopee_staging2")

    # Tạo đối tượng cursor
    cur = myconn.cursor()

    for index, row in df_category.iterrows():
        query = "INSERT INTO category (category_id, category_name, shopid) VALUES (%s, %s, %s)"
        data = (row['category_id'], row['category_name'], row['shopid'])
        cur.execute(query, data)
        myconn.commit()

    print("Data inserted successfully")

except mysql.connector.Error as e:
    print("Error:", e)
    myconn.rollback()

finally:
    # Đóng đối tượng cursor và kết nối
    if myconn.is_connected():
        cur.close()
        myconn.close()
        print("MySQL connection closed")

"""**2. Shop**"""

df_shop = df_shop.drop_duplicates()

df_shop['ctime'] = pd.to_datetime(df_shop['ctime'], unit='s')
df_shop['create_date'] = df_shop['ctime'].dt.date
df_shop['create_time'] = df_shop['ctime'].dt.time

df_shop['shop_rating'] = df_shop['shop_rating'].apply(ast.literal_eval)
df_shop[['rating_normal', 'rating_bad', 'rating_good']] = pd.DataFrame(df_shop['shop_rating'].tolist(), index=df_shop.index)

#thêm các cột cần thiết từ shop_products sang shop_details
all_shops_mapping_1 = df_product[['shopid', 'is_official_shop', 'is_mart', 'is_preferred_plus_seller']].drop_duplicates()
df_shop = pd.merge(df_shop, all_shops_mapping_1, on='shopid', how='left')

df_shop['is_shopee_verified'] = df_shop['is_shopee_verified'].astype(str)
df_shop['is_preferred_plus_seller'] = df_shop['is_preferred_plus_seller'].astype(str)

#Một số shop The address is not public và k công khai dữ liệu và mấy trường khác chưa được xác minh
df_shop['is_mart'] = df_shop['is_mart'].fillna('Unverified')
df_shop['is_official_shop'] = df_shop['is_official_shop'].fillna('Unverified')
df_shop['is_mart'] = df_shop['is_mart'].fillna('Unverified')
df_shop['is_preferred_plus_seller'] = df_shop['is_preferred_plus_seller'].fillna('Unverified')
df_shop['is_shopee_verified'] = df_shop['is_shopee_verified'].replace('False', 'True')
df_shop['is_preferred_plus_seller'] = df_shop['is_preferred_plus_seller'].replace('False', 'True')

df_shop = df_shop.drop(['show_official_shop_label', 'shop_rating', 'seller_metrics', 'ctime'], axis = 1)

#Tạo cột mới để lọc
df_shop['follower_around_number'] = 'Dưới 50.000'
df_shop.loc[df_shop['follower_count'] >= 50000, 'follower_around_number'] = 'Từ 50.000 đến 200.000'
df_shop.loc[df_shop['follower_count'] > 200000, 'follower_around_number'] = 'Trên 200.000'

df_product = pd.read_csv('D:\Final project program\Data\shop_products.csv', low_memory=False)

df_shop

# Commented out IPython magic to ensure Python compatibility.
try:
    # Tạo đối tượng connection
    myconn = mysql.connector.connect(host="localhost", user="root", passwd="Thuy281001", database="shopee_staging2")

    # Tạo đối tượng cursor
    cur = myconn.cursor()

    for index, row in df_shop.iterrows():
        query = """
        INSERT INTO shop (
            shopid, userid, username, shop_name, follower_around_number, follower_count, create_date, create_time,
            rating_star, item_count, response_rate, rating_normal,
            rating_bad, rating_good, is_shopee_verified,
            is_mart, is_preferred_plus_seller
        )
        VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
        )
        """

        data = (
            row['shopid'], row['userid'], row['username'], row['name'], row['follower_around_number'],
            row['follower_count'], row['create_date'], row['create_time'],
            row['rating_star'], row['item_count'], row['response_rate'],
            row['rating_normal'], row['rating_bad'], row['rating_good'],
            row['is_shopee_verified'], row['is_mart'], row['is_preferred_plus_seller']
        )

        cur.execute(query, data)
        myconn.commit()

    print("Data inserted successfully")

except mysql.connector.Error as e:
    print("Error:", e)
    myconn.rollback()

finally:
    # Đóng đối tượng cursor và kết nối
    if myconn.is_connected():
        cur.close()
        myconn.close()
        print("MySQL connection closed")

"""**3. Shope Category**"""

df_shop_category

df_shop_category = df_shop_category.drop(['category_type', 'collection_type'], axis=1)

df_shop_category.dtypes

# Commented out IPython magic to ensure Python compatibility.
try:
    # Tạo đối tượng connection
    myconn = mysql.connector.connect(host="localhost", user="root", passwd="Thuy281001", database="shopee_staging2")

    # Tạo đối tượng cursor
    cur = myconn.cursor()

    for index, row in df_shop_category.iterrows():
        
        query = """
        INSERT INTO shop_category (
            shop_category_id, display_name, shopid, total
        )
        VALUES (
            %s, %s, %s, %s
        )
        """
        data = (
            row['shop_category_id'], row['display_name'], row['shopid'], row['total']
        )

        cur.execute(query, data)
        myconn.commit()

    print("Data inserted successfully into shop_categories")

except mysql.connector.Error as e:
    print("Error:", e)
    myconn.rollback()

finally:
    # Đóng đối tượng cursor và kết nối
    if myconn.is_connected():
        cur.close()
        myconn.close()
        print("MySQL connection closed")

"""**4. Product**"""

df_product.head(3)

# Chuyển đổi trường ctime từ định dạng Linux sang định dạng Windows
df_product['ctime'] = pd.to_datetime(df_product['ctime'], unit='s')
df_product['product_creation_date'] = df_product['ctime'].dt.date
df_product['product_creation_time'] = df_product['ctime'].dt.time

#Tách cột voucher_info
df_product['voucher_id'] = df_product['voucher_info'].apply(lambda x: x.split(',')[0].replace("{'promotion_id':", "") if isinstance(x, str) else None)
df_product['voucher_code'] = df_product['voucher_info'].apply(lambda x: x.split(',')[1].replace("'voucher_code':", "").replace("'", "") if isinstance(x, str) else None)
df_product['voucher_label'] = df_product['voucher_info'].apply(lambda x: x.split(',')[2].replace("'label':", "").replace("'", "").replace("}", "") if isinstance(x, str) else None)
#Tách trường add_on_deal_info
df_product['add_on_deal_id'] = df_product['add_on_deal_info'].apply(lambda x: x.split(',')[0].replace("{'add_on_deal_id': ", "") if isinstance(x, str) else None)
df_product['add_on_deal_label'] = df_product['add_on_deal_info'].apply(lambda x: x.split(',')[1].replace("'add_on_deal_label':", "").replace("'", "") if isinstance(x,str) else None)
# => Xóa cột add_on_deal_info
df_product['bundle_deal_label'] = df_product['bundle_deal_info'].apply(lambda x: x.split(',')[1].replace("'bundle_deal_label': ", "").replace("'", "").replace("}", "") if isinstance(x, str) else None)
# => Xóa cột bundle_deal_info
#tách cột deep_discount_skin
df_product['deep_promotion_price'] = df_product['deep_discount_skin'].apply(lambda x: x.split(',')[3].replace("'skin_data': {'promo_label': {'promotion_price': '₫ ", "").replace("'", "").replace(".", "").replace(" ", "") if isinstance(x, str) else None)
df_product['hidden_promotion_price'] = df_product['deep_discount_skin'].apply(lambda x: x.split(',')[4].replace("'hidden_promotion_price': ", "").replace("'", "").replace(" ","")  if isinstance(x, str) else None)
df_product['deep_start_time'] = df_product['deep_discount_skin'].apply(lambda x: x.split(',')[5].replace("'start_time': ", "").replace("'", "").replace(" ","")  if isinstance(x, str) else None)
df_product['deep_end_time'] = df_product['deep_discount_skin'].apply(lambda x: x.split(',')[6].replace("'end_time': ", "").replace("'", "").replace("}}}", "").replace(" ","") if isinstance(x, str) else None)
# => Xóa cột deep_discount_skin
#Tách cột exclusive_price_info
df_product['exclusive_price_promotion_id'] = df_product['exclusive_price_info'].apply(lambda x: x.split(',')[0].replace("{'exclusive_price_results': [{'promotion_id': ", "") if isinstance(x,str) else None)
df_product['exclusive_save_amount'] = df_product['exclusive_price_info'].apply(lambda x: x.split(',')[2].replace("'save_amount': ", "").replace(" ", "") if isinstance(x,str) else None)
df_product['exclusive_label'] = df_product['exclusive_price_info'].apply(lambda x: x.split(',')[7].replace("'label': ", "").replace("'", "") if isinstance(x,str) else None)
df_product['exclusive_url'] = df_product['exclusive_price_info'].apply(lambda x: x.split(',')[8].replace("'url': ", "").replace("'", "") if isinstance(x,str) else None)
df_product['exclusive_url_text'] = df_product['exclusive_price_info'].apply(lambda x: x.split(',')[9].replace("'url_text': ", "").replace("'", "") if isinstance(x,str) else None)
df_product['exclusive_model_ep_price'] = df_product['exclusive_price_info'].apply(lambda x: x.split(',')[13].replace("'model_ep_price': ", "").replace("'", "").replace(" ", "") if isinstance(x,str) else None)
df_product['exclusive_model_ep_discount'] = df_product['exclusive_price_info'].apply(lambda x: x.split(',')[14].replace("'model_ep_discount': ", "").replace("'", "").replace("}]}", "") if isinstance(x,str) else None)
# => Xóa cột exclusive_price_info
#Tách cột tier_variation
df_product['name_tier_variation'] = df_product['tier_variations'].apply(lambda x: x.split(',')[0].replace("[{'name': ", "").replace("'", "") if isinstance(x,str) else None)
df_product['option_variation'] = df_product['tier_variations'].apply(lambda x: re.findall(r"'options': \[(.*?)\]", x)[0].split(", ") if isinstance(x, str) else None)
# => Xóa cột tier_variation

df_product['voucher_id'] = df_product['voucher_id'].astype(float) / 10**5

df_product['name_tier_variation'] = df_product['name_tier_variation'].astype(str)
df_product['option_variation'] = df_product['option_variation'].astype(str)

df_product['option_variation'] = df_product['option_variation'].replace(["''", "'O'"], np.nan)

#Tạo cột mới
df_product['voucher_cash_discount'] = df_product['voucher_label']
df_product['voucher_percentage'] = df_product['voucher_label']
df_product['voucher_coin_refund'] = df_product['voucher_label']

df_product['voucher_cash_discount'] = np.where(df_product['voucher_label'].str.contains('₫'), df_product['voucher_cash_discount'], np.nan)
df_product['voucher_percentage'] = np.where(df_product['voucher_label'].str.contains('% Giảm'), df_product['voucher_percentage'], np.nan)
df_product['voucher_coin_refund'] = np.where(df_product['voucher_label'].str.contains('xu'), df_product['voucher_coin_refund'], np.nan)

df_product['voucher_cash_discount'] = df_product['voucher_cash_discount'].str.replace('Giảm ₫', '').str.replace('k', '000').str.replace('tr', '000000')
df_product['voucher_coin_refund'] = df_product['voucher_coin_refund'].str.replace('Hoàn ', '').str.replace('% xu', '')
df_product['voucher_percentage'] = df_product['voucher_percentage'].str.replace('% Giảm', '')

df_product['voucher_cash_discount'] = df_product['voucher_cash_discount'].fillna(0)
df_product['voucher_coin_refund'] = df_product['voucher_coin_refund'].fillna(0)
df_product['voucher_percentage'] = df_product['voucher_percentage'].fillna(0)

# Chuyển đổi các trường sang kiểu numeric và xử lý giá trị không hợp lệ
df_product['exclusive_model_ep_price'] = pd.to_numeric(df_product['exclusive_model_ep_price'], errors='coerce')
df_product['exclusive_save_amount'] = pd.to_numeric(df_product['exclusive_save_amount'], errors='coerce')
df_product['deep_promotion_price'] = pd.to_numeric(df_product['deep_promotion_price'], errors='coerce')

#Chỉnh giá của sản phẩm, thừa 5 số 0
fields_to_reduce = ['price', 'price_min', 'price_max', 'price_min_before_discount', 'price_max_before_discount', 'price_before_discount', 'exclusive_model_ep_price', 'exclusive_save_amount']
df_product[fields_to_reduce] = df_product[fields_to_reduce].apply(lambda x: x // 100000)

df_product['discount_name'] = df_product['name']
#Code cũ
def extract_score(row):
    if isinstance(row, str):
        start_index = row.find("[")
        if start_index != -1:
            start_index += len("[")
            end_index = row.find("]", start_index)
            score = row[start_index:end_index]
            if "giảm" in score.lower() or "nhập" in score.lower():
                return score
    return 0

df_product['discount_name'] = df_product['name'].apply(extract_score)
print(df_product['discount_name'])

df_product['discount_condition_code'] = df_product['discount_name']
df_product['discount_condition_percentage'] = df_product['discount_name']
df_product['discount_condition_cash'] = df_product['discount_name']
df_product['condition'] = df_product['discount_name']

df_product['discount_condition_code'] = df_product['discount_condition_code'].astype(str)

def extract_code(row):
    pattern = r'\bMã\s*([A-Za-z0-9]+)\b'
    match = re.search(pattern, row)
    if match:
        return match.group(1)
    return ''

df_product['discount_condition_code'] = df_product['discount_condition_code'].apply(extract_code)

# In kết quả
print(df_product['discount_condition_code'])

df_product['discount_condition_code'] = df_product['discount_condition_code'].replace('', np.nan)

df_product['discount_condition_percentage'] = df_product['discount_name'].astype(str)
df_product['discount_condition_cash'] = df_product['discount_name'].astype(str)
df_product['condition_discount'] = df_product['discount_name'].astype(str)

df_product['discount_condition_percentage'] = np.where(df_product['discount_name'].str.contains('%'), df_product['discount_condition_percentage'], np.nan)
df_product['discount_condition_cash'] = np.where(df_product['discount_name'].str.contains('%'), np.nan, df_product['discount_condition_cash'])
df_product['condition_discount'] = np.where(df_product['discount_name'].str.contains('đơn'), df_product['condition_discount'], np.nan)

df_product['condition_discount'] = df_product['condition_discount'].str.split('đơn ').str[-1]

def extract_score(row):
    if isinstance(row, str):
        start_index = row.find("m ")
        if start_index != -1:
            start_index += len("m ")
            end_index = row.find("%", start_index)
            score = row[start_index:end_index]
            return score
    return 0
df_product['discount_condition_percentage'] = df_product['discount_condition_percentage'].apply(extract_score)
# In kết quả
print(df_product['discount_condition_percentage'])
#=>Xóa cột info

df_product['discount_condition_percentage'] = df_product['discount_condition_percentage'].str.replace('thêm ', '')

df_product['discount_condition_cash'] = df_product['discount_condition_cash'].str.split('m ').str[-1]

df_product['discount_condition_cash'] = df_product['discount_condition_cash'].str.split('đơn|Đơn').str[0]

#cần thay trước
df_product['condition_discount'] = df_product['condition_discount'].str.replace("1TR5", "1500000")
df_product['discount_condition_cash'] = df_product['discount_condition_cash'].str.replace("1Tr2", "1200000").str.replace("2.2TR", "2200000").str.replace("2TR5", "2500000").str.replace("1,5 Triệu", "1500000").str.replace("1 Triệu", "1000000").str.replace("1TR7", "1700000").str.replace("1TR5", "1500000").str.replace("1,5Tr", "1500000")

df_product['discount_condition_percentage'] = df_product['discount_condition_percentage'].str.replace("thêm ", "")
df_product['discount_condition_cash'] = df_product['discount_condition_cash'].str.replace("đến", "").str.replace("Ngay", "").str.replace("tới", "").str.replace("k", "000").str.replace("K", "000").str.replace("TR", "000000").str.replace("Tr", "000000").str.replace(".", "").str.replace(" ", "")
df_product['condition_discount'] = df_product['condition_discount'].str.replace("từ ", "").str.replace(" tối đa 200K", "").str.replace("K", "000").str.replace("TR", "000000").str.replace("đ", "").str.replace("Đ", "").str.replace("k", "000")

df_product['discount_condition_percentage'] = df_product['discount_condition_percentage'].fillna(0)
df_product['discount_condition_cash'] = df_product['discount_condition_cash'].fillna(0)
df_product['condition_discount'] = df_product['condition_discount'].fillna(0)

df_product['condition_discount'].value_counts() #đổi trường này thành condition_discount

def extract_product_name(name):
    start_index = name.find('[')
    end_index = name.find(']')
    if start_index != -1 and end_index != -1:
        return name[:start_index] + name[end_index+1:].strip()
    return name

# Áp dụng hàm chuyển đổi cho cột 'name' và tạo cột 'product_name' mới
df_product['product_name'] = df_product['name'].apply(extract_product_name)
df_product['product_name'] = df_product['product_name'].str.replace('-', '').str.strip()

# In kết quả
print(df_product['product_name'])

df_product['buy'] = df_product['bundle_deal_label']
df_product['get_off_cash'] = df_product['bundle_deal_label']
df_product['get_off_percentage'] = df_product['bundle_deal_label']

df_product['buy'] = np.where(df_product['bundle_deal_label'].str.contains('Mua'), df_product['bundle_deal_label'], np.nan)
df_product['get_off_cash'] = np.where(df_product['bundle_deal_label'].str.contains('₫'), df_product['bundle_deal_label'], np.nan)
df_product['get_off_percentage'] = np.where(df_product['bundle_deal_label'].str.contains('%'), df_product['bundle_deal_label'], np.nan)

df_product['buy'] = df_product['bundle_deal_label'].str.extract(r'Mua (\d+)', expand=False).fillna(0)

df_product['get_off_cash'] = df_product['bundle_deal_label'].str.extract(r'₫([0-9,.]+)').fillna(0)
df_product['get_off_cash'] = df_product['get_off_cash'].str.replace(".", "")

df_product['get_off_cash'] = df_product['get_off_cash'].fillna(0)
df_product['buy'] = df_product['get_off_cash'].fillna(0)
df_product['get_off_percentage'] = df_product['get_off_cash'].fillna(0)

df_product['get_off_percentage'] = df_product['bundle_deal_label'].str.extract(r'(\d+)%').fillna(0).astype(int)

df_product['buy'] = df_product['buy'].astype(int)
df_product['get_off_cash'] = df_product['get_off_cash'].astype(int)
df_product['get_off_percentage'] = df_product['get_off_percentage'].astype(int)

df_product['deep_start_time'].unique()

def extract_option(row):
    if isinstance(row,str):
        start_index = row.find("'options': [")
        if start_index != -1:
            start_index += len("'options': [")
            end_index = row.find("]", start_index)
            option = row[start_index:end_index]
            return option
    return 0
df_product['option_variation'] = df_product['tier_variations'].apply(extract_option)

print(df_product['option_variation'])

# Hàm biến đổi giá trị cột "name_variation"
def transform_name_variation(value):
    transformation_dict = {
        'Phân Loại': 'Màu sắc',
        'Màu': 'Màu sắc',
        'Hàng': 'Hàng',
        'N': 'Phân loại',
        'Màu sắc': 'Màu sắc',
        'Hang': 'Hàng',
        'Color': 'Màu sắc',
        'Name': 'Tên',
        'Màu sắc': 'Màu sắc',
        'Kiểu Dáng': 'Kiểu dáng',
        'Nhóm màu': 'Màu sắc',
        'Variation': 'Biến thể',
        'Model': 'Kiểu dáng',
        'Số lượng': 'Số lượng',
        'Dung Tích': 'Dung tích',
        'lựa chọn': 'Lựa chọn',
        'NV0001': 'NV0001',
        'màu': 'Màu sắc',
        'LỰA CHỌN': 'Lựa chọn',
        'mã': 'Mã',
        '36T1': '36T1',
        'Loại': 'Phân loại',
        'màu sắc': 'Màu sắc',
        'PHÂN LOẠI': 'Phân loại',
        'mã': 'Mã',
        'Màu Sắc': 'Màu sắc',
        'màu sắ': 'Màu sắc',
        'BH': 'Bảo hành',
        'Mã': 'Mã',
        'DiiiB': 'DiiiB',
        'Kích Thước': 'Kích thước',
        'Arenti': 'Arenti',
        'Deerma': 'Deerma',
        'Phiên Bản': 'Phiên bản',
        'Màu săc': 'Màu sắc',
        'MÀU SẮC': 'Màu sắc',
        'Phụ kiên U2': 'Phụ kiện U2',
        '950': '950',
        'pk': 'Phụ kiện',
        'Miếng mút': 'Miếng mút',
        'ROBOT N10': 'ROBOT N10',
        'SÁP THƠM': 'Sáp thơm',
        'T10': 'T10',
        'Cụm động cơ': 'Cụm động cơ',
        'ROBOT T8 MAX': 'ROBOT T8 MAX',
        'Cụm động cơ': 'Cụm động cơ',
        'ROBOT T8 MAX': 'ROBOT T8 MAX',
        'Robot hút bụi': 'Robot hút bụi',
        'Cảm biến': 'Cảm biến',
        'Cụm bánh lái': 'Cụm bánh lái',
        'cụm bánh xe': 'Cụm bánh xe',
        'CBR chổi ven': 'CBR chổi ven',
        'Cảm biến CR': 'Cảm biến CR',
        'Hộp đựng nước': 'Hộp đựng nước',
        'Variations': 'Biến thể',
        'Balô': 'Balô',
        'phân loại': 'Phân loại',
        'Halo Speaker': 'Halo Speaker',
        'Phân lọai': 'Phân loại',
        'Biến thể': 'Biến thể',
        'Bang Mini': 'Bang Mini',
        'Water Purifier': 'Máy lọc nước',
        'Air Purifier': 'Máy lọc không khí',
        'WP': 'Máy lọc nước',
        'AP': 'Máy lọc không khí',
        'Dung tích': 'Dung tích',
        'Linh kiện': 'Linh kiện',
        '1859000': '1859000',
        'Dịch vụ kèm': 'Dịch vụ kèm',
        'MÃ SKU': 'Mã SKU',
        'MÃ': 'Mã',
        'Đường kính': 'Đường kính',
        'Dịch vụ': 'Dịch vụ',
        'Mẫu': 'Mẫu',
        'Kỹ thuật': 'Kỹ thuật',
        'Thanh lý/mới': 'Thanh lý/mới',
        'SKU': 'SKU',
        'Dòng điều hòa': 'Dòng điều hòa',
        'Loại tủ': 'Loại tủ',
        'Loại máy': 'Loại máy',
        'Loại Máy': 'Loại máy',
        'Nồi cơm điện': 'Nồi cơm điện',
        'Màu sẵc': 'Màu sắc',
        'Ca Lẩu Điện': 'Ca lẩu điện',
        'Máy Xay Thịt': 'Máy xay thịt',
        'Hút Chân Không': 'Máy hút chân không',
        'Nồi Chiên': 'Nồi chiên',
        'Máy Làm Mì': 'Máy làm mì',
        'Color Family': 'Nhóm màu',
        'Size': 'Kích cỡ',
        'Lõi lọc': 'Lõi lọc',
        'Bộ nồi': 'Bộ nồi',
        'Motor': 'Động cơ',
        'PW-8207': 'PW-8207',
        'Hiệu': 'Hiệu',
        'F-LSD10': 'F-LSD10',
        'COMBO': 'COMBO',
        'COMBO HỘP': 'COMBO HỘP',
        'DÒNG MÁY': 'Dòng máy',
        'Mã hàng': 'Mã hàng',
        'F-LSA10': 'F-LSA10',
        'PW-059': 'PW-059',
        'F-LSA20': 'F-LSA20',
        'CV-BF16': 'CV-BF16',
        'KGC-712CB': 'KGC-712CB',
        'PW-069H': 'PW-069H',
        'Dao': 'Dao',
        'A-801': 'A-801',
        'Chảo': 'Chảo',
        'size sản phẩm': 'Kích cỡ',
        'SIZE': 'Kích cỡ',
        'Bộ sản phẩm': 'Bộ sản phẩm',
        'Đen': 'Đen',
        'Ultima': 'Ultima',
        'PW-039H': 'PW-039H',
        'CV-SF20V': 'CV-SF20V',
        'MK-102': 'MK-102',
        'CV-SF18': 'CV-SF18',
        'size': 'Kích cỡ',
        'Bộ': 'Bộ',
        'Máu sắc': 'Máu sắc',
        'SM-TF46LS': 'SM-TF46LS',
        'LV16-RV': 'LV16-RV',
        'CV-940': 'CV-940',
        'EL-5208': 'EL-5208',
        'LWR-A092': 'LWR-A092',
        'PW-029': 'PW-029',
        'I-68': 'I-68',
        'A-802': 'A-802',
        'RWF-W1664TV': 'RWF-W1664TV',
        'EL-5204': 'EL-5204',
        'EL-6304': 'EL-6304',
        'EL0739': 'EL0739',
        'Hitachi SF16': 'Hitachi SF16',
        'PW039H': 'PW-039H',
        'ZT45': 'ZT45',
        'ZK808': 'ZK808',
        'PW069H': 'PW-069H',
        'RWF-W1830BV': 'RWF-W1830BV',
        'RWF-W1669BV': 'RWF-W1669BV',
        'NS-321CBM2': 'NS-321CBM2',
        'CV-960F': 'CV-960F',
        'EC685': 'EC685',
        'SC22V': 'SC22V',
        'Model (Màu)': 'Màu sắc',
        'Dòng máy': 'Dòng máy',
        'Dòng điện thoạ': 'Dòng điện thoại',
        'KAROFI': 'KAROFI',
        'OPTIMUS PLUS': 'OPTIMUS PLUS',
        'KAD-D66S': 'KAD-D66S',
        'Chọn màu nhé!': 'Màu sắc',
        'GC-18IS33': 'GC-18IS33',
        'GH-09IS33': 'GH-09IS33',
        'p300l': 'p300l',
        'Unilever': 'Unilever',
        'Chọn mẫu :': 'Chọn mẫu',
        'Chọn Màu Size': 'Chọn màu kích cỡ',
        'Chọn mẫu:': 'Chọn mẫu',
        'Chọn Dung tích': 'Chọn dung tích',
        'Chọn Mẫu :': 'Chọn mẫu',
        'Màu Size': 'Màu kích cỡ',
        'Chọn Mẫu:': 'Chọn mẫu',
        'Chọn mẫu': 'Chọn mẫu',
        'Hương Thơm': 'Hương thơm',
        'Mã (Màu)': 'Mã màu',
        'MÀU': 'Màu',
        'Kiểu': 'Kiểu',
        'Mùi hương': 'Mùi hương',
        'Bếp': 'Bếp',
        'Mã sản Phẩm': 'Mã sản phẩm',
        'CHỌN': 'Chọn',
        'CHỌN SỐ LƯỢNG': 'Chọn số lượng',
        'CHỌN THÊM': 'Chọn thêm',
        '123': '123',
        'CHỌN MẪU MÁY': 'Chọn mẫu máy',
        'CHỌN MẪU BẾP': 'Chọn mẫu bếp',
        'Cây nước': 'Cây nước',
        'CHỌN SỐ LÕI': 'Chọn số lõi',
        'Loại Nồi': 'Loại nồi',
        'Màu trắng': 'Màu trắng',
        'CHỌN MÀU/LOẠI': 'Chọn màu/loại',
        'CHỌN LOẠI MÁY': 'Chọn loại máy',
        'CHỌN MUA': 'Chọn mua',
        'CHỌN LOẠI BẾP': 'Chọn loại bếp',
        'CHỌN MÁY': 'Chọn máy',
        'KÍCH THƯỚC': 'Kích thước',
        'Hút mùi': 'Hút mùi',
        'Đường Kính': 'Đường kính',
        'Loại bếp': 'Loại bếp',
        'Loại linh kiện': 'Loại linh kiện',
        'korihome': 'korihome',
        'Nhóm Màu': 'Nhóm màu',
        'SC-09IS33': 'SC-09IS33',
        'Tầng': 'Tầng',
        'GC-09IS33': 'GC-09IS33',
        'Thể Tích': 'Thể tích',
        'LC-09FS33': 'LC-09FS33',
        'Lõi Korihome': 'Lõi korihome',
        'PPI82560MS': 'PPI82560MS',
        'GC-12IS33': 'GC-12IS33',
        'SC-18FS32': 'SC-18FS32',
        'Forseti': 'Forseti',
        'MSMA3-10CRN1': 'MSMA3-10CRN1',
        'GH-12IS33': 'GH-12IS33',
        'MSAFB-13HRN1': 'MSAFB-13HRN1',
        'MSAFG-13CRN8': 'MSAFG-13CRN8',
        'SC-12FS33': 'SC-12FS33',
        'MSMA1-13CRN1': 'MSMA1-13CRN1',
        'MSAG-10CRND8': 'MSAG-10CRND8',
        'karofi': 'karofi',
        'Karofi': 'karofi',
        'SH-18FS32': 'SH-18FS32',
        'SH-09FS32': 'SH-09FS32',
        'Casper 32 inch': 'Casper 32 inch',
        'MSAFB-10HRN1': 'MSAFB-10HRN1',
        'MSMA1-10CRDN1': 'MSMA1-10CRDN1',
        'MSAFB-13CRN8': 'MSAFB-13CRN8',
        'Hình': 'Hình',
        'GH-12TL32': 'GH-12TL32',
        'V10ENW1': 'V10ENW1',
        'BE326SI': 'BE326SI',
        'BE32GT': 'BE32GT',
        'Kangaroo': 'Kangaroo',
        'MSAFG-10CRN8': 'MSAFG-10CRN8',
        'MSMA1-10CRN1': 'MSMA1-10CRN1',
        'BE328SE': 'BE328SE',
        'TG-DT2022A': 'TG-DT2022A',
        'Lõi lọc nước': 'Lõi lọc nước',
        'MODEL': 'Kiểu dáng',
    'Máy lọc nước': 'Máy lọc nước',
    'CHẢO ĐÁ SÂU': 'Chảo đá sâu',
    'NỒI ĐÁ': 'Nồi đá',
    'Mùa sắc': 'Màu sắc',
    'Philips': 'Philips',
    'Size núm': 'Kích thước núm',
    'Cạo râu': 'Cạo râu',
    'MQ5235': 'MQ5235',
    'Braun': 'Braun',
    'Braun 5235': 'Braun 5235',
    'Nồi yến': 'Nồi yến',
    'Máy xay': 'Máy xay',
    'Chiên': 'Chiên',
    'Hans H10': 'Hans H10',
    'Bóng': 'Bóng',
    'MQ5000': 'MQ5000',
    'Ủi': 'Ủi',
    'Bình': 'Bình',
    'xay': 'xay',
    'Nồi chiên': 'Nồi chiên',
    'Máy vắt cam': 'Máy vắt cam',
    'Đèn sưởi': 'Đèn sưởi',
    'Tỏi': 'Tỏi',
    'Combo 3 món': 'Combo 3 món',
    'Combo': 'Combo',
    'Máy xay cầm tay': 'Máy xay cầm tay',
    'Màu xanh ngọc': 'Màu xanh ngọc',
    'Combo 2': 'Combo 2',
    'Bộ 2 chảo': 'Bộ 2 chảo',
    'Xanh ngọc': 'Xanh ngọc',
    'Phụ kiện': 'Phụ kiện',
    'Núm': 'Núm',
    'Combo 3': 'Combo 3',
    'MQ5045': 'MQ5045',
    'HA': 'HA',
    'Xay': 'Xay',
    'Phân loại hàng': 'Phân loại hàng',
    'Bình sữa': 'Bình sữa',
    'Sưởi': 'Sưởi',
    'Tùy chọn': 'Tùy chọn',
    'máy xay vắt': 'Máy xay vắt',
    'bàn chải điện': 'Bàn chải điện',
    'Nồi cơm mini': 'Nồi cơm mini',
    'MÁY XAY MASUTO': 'Máy xay Masuto',
    'Máy xay vắt': 'Máy xay vắt',
    'nồi lẩu điện': 'Nồi lẩu điện',
    'Ấm thủy tinh': 'Ấm thủy tinh',
    'Nồi cơm': 'Nồi cơm',
    'Bảo hành': 'Bảo hành',
    'Bảo Hành': 'Bảo hành',
    'model': 'Kiểu dáng',
    'màu sắc': 'Màu sắc',
    'AL-HCK21': 'AL-HCK21',
    '1': '1',
    'PHIÊN BẢN': 'Phiên bản',
    'Bộ lau nhà': 'Bộ lau nhà',
    'Xửng hấp': 'Xửng hấp',
    'Loại vỉ': 'Loại vỉ',
    'Mk311': 'Mk311',
    'Công suất': 'Công suất',
    'mẫu': 'Mẫu',
    'Vui lòng chọn:': 'Vui lòng chọn:',
    'Loại Ổ Cắm': 'Loại ổ cắm',
    'Sản Phẩm': 'Sản phẩm',
    'chọn mẫu': 'Chọn mẫu',
    'Chọn loại': 'Chọn loại',
    'Cổng USB': 'Cổng USB',
    'Loại đèn': 'Loại đèn',
    'Vui lòng CHỌN:': 'Vui lòng chọn:',
    'Mã sản phẩm': 'Mã sản phẩm',
    'Vui lòng CHỌN': 'Vui lòng chọn',
    'Chọn công suất': 'Chọn công suất',
    'Vui lòng chọn': 'Vui lòng chọn',
    'Phi ống': 'Phi ống',
    'ỐP NỔI TRÒN': 'Ốp nổi tròn',
    'Chọn CÔNG SUẤT': 'Chọn công suất',
    'Chọn Màu sắc:': 'Chọn màu sắc:',
    'MẪU MÃ': 'Mẫu mã',
    'Mẫu mã': 'Mẫu mã',
    'LOẠI SP': 'Loại sản phẩm',
    'DUNG TÍCH': 'Dung tích',
    'MẪU': 'Mẫu',
    'MÀU SẮC Ô DÙ': 'Màu sắc ô dù',
    'Bơm Tự Động': 'Bơm tự động',
    'Dòng Máy': 'Dòng máy',
    'PL Sản Phẩm': 'PL sản phẩm',
    'Mã SP': 'Mã sản phẩm',
    'Tên SP': 'Tên sản phẩm',
    'ĐỘ DÀI': 'Độ dài',
    'Mã Iphone': 'Mã iPhone',
    'Phân loại SP': 'Phân loại sản phẩm',
    'MÀU DÂY': 'Màu sắc',
    'Phân Loại SP': 'Phân loại sản phẩm',
'Đèn thông minh': 'Đèn thông minh',
'Đèn cảm biến': 'Đèn cảm biến',
'Đèn ngủ': 'Đèn ngủ',
'Lightstrip 1S': 'Lightstrip 1S',
'Kích Thước Đèn': 'Kích thước đèn',
'Đèn Z1': 'Đèn Z1',
'Led dây tóc': 'Led dây tóc',
'Đèn trần': 'Đèn trần',
'Đèn bàn V1': 'Đèn bàn V1',
'Đèn âm trần M2': 'Đèn âm trần M2',
'Đèn nến Candel': 'Đèn nến Candel',
'Đèn trần Halo': 'Đèn trần Halo',
'Thiết Bị': 'Thiết bị',
'GÓI FPT PLAY': 'Gói FPT Play',
'GÓI': 'Gói',
'Gói Vip': 'Gói VIP',
'Gói Max': 'Gói Max',
'Option (Mô Tả)': 'Option (Mô tả)',
'Nhà mạng': 'Nhà mạng',
'Option (Mô tả)': 'Option (Mô tả)',
'Cổng chuyển': 'Cổng chuyển',
'Qùa tặng': 'Quà tặng',
'Chân': 'Chân',
'Maù sắc': 'Màu sắc',
'Độ dài': 'Độ dài',
'BỘ SẠC 20W': 'Bộ sạc 20W',
'BỘ SẠC SAMSUNG': 'Bộ sạc Samsung',
'ĐỜI MÁY': 'Đời máy',
'hình dạng': 'Hình dạng',
'TAI ZUZG': 'Tai ZUZG',
'TAI NGHE ZIN': 'Tai nghe ZIN',
'TAI NGHE': 'Tai nghe',
'CÁP SẠC IP': 'Cáp sạc iPhone',
'SẠC DỰ PHÒNG': 'Sạc dự phòng',
'hình dáng': 'Hình dáng',
'CÁP YGX1/2/3': 'Cáp YGX1/2/3',
'KÍNH CNT1 ZUZG': 'Kính CNT1 ZUZG',
'BỘ 45W': 'Bộ 45W',
'HỘP ĐỰNG': 'Hộp đựng',
'jack ZUZG': 'Jack ZUZG',
'CÁP SẠC ZUZG': 'Cáp sạc ZUZG',
'JACK CHUYỂN': 'Jack chuyển',
'TAI NGHE AKG': 'Tai nghe AKG',
'CỦ SẠC NHANH': 'Củ sạc nhanh',
'MÀU KÍNH': 'Màu kính',
'ẢNH': 'Ảnh',
'củ sạc cáp sạc': 'Củ sạc cáp sạc',
'BỘ SẠC U01S': 'Bộ sạc U01S',
'CÁP SẠC NHANH': 'Cáp sạc nhanh',
'FULL DẺO ZUZG': 'Full dẻo ZUZG',
'CÁP ZUZG': 'Cáp ZUZG',
'TẨU SẠC': 'Tẩu sạc',
'CÁP NY0': 'Cáp NY0',
'CÁP BA ĐẦU': 'Cáp ba đầu',
'Con vật': 'Con vật',
'Chiều dài': 'Chiều dài',
'GIÁ ĐỠ DT': 'Giá đỡ điện thoại',
'cáp ba đầu': 'Cáp ba đầu',
'Củ Sạc ZUZG': 'Củ sạc ZUZG',
'TẨU Ô TÔ': 'Tẩu ô tô',
'DOCK SẠC ZUZG': 'Dock sạc ZUZG',
'MÀU NGẪU NHIÊN': 'Màu ngẫu nhiên',
'P60': 'P60',
'p28 plus': 'P28 Plus',
'P8 MAX': 'P8 Max',
'C61': 'C61',
'L10': 'L10',
'p28plus': 'P28 Plus',
'C60': 'C60',
'C81': 'C81',
'P30': 'P30',
'p8 max': 'P8 Max',
'V33': 'V33',
'P8MAX': 'P8 Max',
'C80': 'C80',
'p8max': 'P8 Max',
'i11': 'i11',
'color': 'Màu sắc',
'Plug Type': 'Loại ổ cắm',
'Sức chứa': 'Sức chứa',
'Options': 'Option',
'Màu': 'Màu',
'Đời': 'Đời',
'Mẫu loa': 'Mẫu loa',
'đời': 'Đời',
'Kết Nối': 'Kết nối',
'YS97': 'YS97',
'Tên': 'Tên',
'Phân loại': 'Phân loại',
'MÀU SẮC': 'Màu sắc',
'Loa Xm-5h': 'Loa Xm-5h',
'sạc dự phòng': 'Sạc dự phòng',
'Stinger 2': 'Stinger 2',
'Gopro': 'Gopro',
'Phiên bản': 'Phiên bản',
'G-Pro': 'G-Pro',
'Nút bắn': 'Nút bắn',
'Loại tim': 'Loại tim',
'độ dài': 'Độ dài',
'Loại dây HDMI': 'Loại dây HDMI',
'Độ dài': 'Độ dài',
'Độ Dài': 'Độ dài',
'Kết nối': 'Kết nối',
'Dung lượng': 'Dung lượng',
'Loại Sạc': 'Loại sạc',
'Dung Lượng': 'Dung lượng',
'Họa tiết': 'Họa tiết',
'Loại màu': 'Loại màu',
'COlor': 'Màu sắc',
'Chuẩn cắm': 'Chuẩn cắm',
'Độ dài dây': 'Độ dài dây',
'Sạc 10000MAH': 'Sạc 10000mAh',
'Case': 'Case',
'Switch': 'Switch',
'Củ sạc': 'Củ sạc',
'Cân': 'Cân',
'Ap2.ap3.apro': 'Ap2.ap3.apro',
'Máy +đầu': 'Máy + đầu',
'sạciphon': 'Sạc iPhone',
'Combo TS-431P3': 'Combo TS-431P3',
'Chọn phân loại': 'Chọn phân loại',
'LOẠI GIÁ ĐỠ': 'Loại giá đỡ',
'CHỌN LOẠI': 'Chọn loại',
'Chọn loa': 'Chọn loa',
'Chọn Loại': 'Chọn loại',
'Chọn Màu': 'Chọn màu',
'Chọn Mẫu': 'Chọn mẫu',
'Chọn loại tai': 'Chọn loại tai',
'Chọn Hình': 'Chọn hình',
'Chọn màu loa': 'Chọn màu loa',
'KHỔ-ĐỘ DÀY': 'Khổ - Độ dày',
'Chọn Loại Loa': 'Chọn loại loa',
'Chọn hình': 'Chọn hình',
'Size - Cỡ chảo': 'Size - Cỡ chảo',
'Size chảo': 'Size chảo',
'Size Chảo': 'Size chảo',
'COLOUR': 'Màu sắc',
'Phân loại bể': 'Phân loại bể',
'Chọn Size': 'Chọn size',
'Loa D202': 'Loa D202',
'MÁY': 'Máy',
'Lựa chọn': 'Lựa chọn',
'LOẠI': 'Loại',
'CHỌN MẪU': 'Chọn mẫu',
'màu đen': 'Màu đen',
'Chọn số lượng': 'Chọn số lượng',
'Thông số': 'Thông số',
'BỂ BƠI': 'Bể bơi',
'Dòng': 'Dòng',
'Chọn mua': 'Chọn mua',
'FEATURE': 'Tính năng',
'type': 'Loại',
'Cấu hình': 'Cấu hình',
'Màu Sẵc': 'Màu sắc',
'Band 8': 'Band 8',
'Freebuds SE': 'Freebuds SE',
'Freebuds 5i': 'Freebuds 5i',
'Band 7': 'Band 7',
'GT3 46mm': 'GT3 46mm',
'Scale 3': 'Scale 3',
'Watch fit 2': 'Watch Fit 2',
'GT3 42mm': 'GT3 42mm',
'GT 3 SE': 'GT 3 SE',
'Sound joy': 'Sound Joy',
'WATCH FIT Mới': 'Watch Fit Mới',
'Freebuds 5': 'Freebuds 5',
'Xám không gian': 'Xám không gian',
'Freebuds pro 2': 'Freebuds Pro 2',
'Kid 4 pro': 'Kid 4 Pro',
'Watch 4': 'Watch 4',
'Watch Buds': 'Watch Buds',
'Bàn phím': 'Bàn phím',
'GT cyber': 'GT Cyber',
'Dòng Pencil': 'Dòng Pencil',
'Loại ốp iPhone': 'Loại ốp iPhone',
'Phân Loại Dòng': 'Phân loại dòng',
'Loại iPad': 'Loại iPad',
'Củ Sạc': 'Củ sạc',
'Loại & Màu': 'Loại & Màu',
'OPPO A16 3GB': 'OPPO A16 3GB',
'Dòng pin': 'Dòng pin',
'Loại Pin': 'Loại pin',
'Loại pin': 'Loại pin',
'Phiên bản': 'Phiên bản',
'Dòng máy iP': 'Dòng máy iPhone',
'Loại cổng': 'Loại cổng',
'iPhone': 'iPhone',
'Điện thoại': 'Điện thoại',
'IPHONE': 'IPHONE',
'Táo': 'Táo',
'Cổng sạc': 'Cổng sạc',
'Chân sạc': 'Chân sạc',
'Đầu vào': 'Đầu vào',
'CHÂN SẠC': 'Chân sạc',
'DUNG LƯỢNG': 'Dung lượng',
'Samsung': 'Samsung',
'CỔNG SẠC': 'Cổng sạc',
'chiều dài': 'Chiều dài',
'Bộ sạc': 'Bộ sạc',
'Chân sạc - Màu': 'Chân sạc - Màu',
'ĐỘ DÀI - MÀU': 'Độ dài - Màu',
'Độ dài - màu': 'Độ dài - Màu',
'Độ dài-Màu sắc': 'Độ dài - Màu sắc',
'Màu-Dài': 'Màu - Dài',
'Màu sắc-Độ dài': 'Màu sắc - Độ dài',
'Loại - màu sắc': 'Loại - Màu sắc',
'ED011': 'ED011',
'Loại-Dài': 'Loại - Dài',
'Loại - màu': 'Loại - Màu',
'Độ dài dây cáp': 'Độ dài dây cáp',
'Màu + Dài': 'Màu + Dài',
'Loại - Màu': 'Loại - Màu',
'Dài': 'Dài',
'Loại - Dài': 'Loại - Dài',
'Chân cắm': 'Chân cắm',
'Độ dài - Màu': 'Độ dài - Màu',
'Màu-Dài-Loại': 'Màu - Dài - Loại',
'Kích thước đt': 'Kích thước điện thoại',
'CM475': 'CM475',
'Remote': 'Remote',
'Thiết kế': 'Thiết kế',
'Số lượng/hộp': 'Số lượng/hộp',
'số lượng/hộp': 'Số lượng/hộp',
'Loại-Màu-Dài': 'Loại - Màu - Dài',
'Chức năng': 'Chức năng',
'Đen Dẹt': 'Đen Dẹt',
'US334': 'US334',
'Loại dây-Dài': 'Loại dây - Dài',
'CHỦNG LOẠI': 'Chủng loại',
'Loại-Độ dài': 'Loại - Độ dài',
'KT màn hình': 'Kích thước màn hình',
'Loại- Dài-Màu': 'Loại - Dài - Màu',
'Màu & độ dài': 'Màu & Độ dài',
'Hoco': 'Hoco',
'cổng kết nối': 'Cổng kết nối',
'Kết Nối': 'Kết nối',
'Cổng Sạc': 'Cổng sạc',
'chân cắm': 'Chân cắm',
'chiều dai': 'Chiều dài',
'kết nối': 'Kết nối',
'nhóm màu': 'Nhóm màu',
'dòng máy': 'Dòng máy',
'Chiều Dài': 'Chiều dài',
'Hoco X45': 'Hoco X45',
'Bộ nhớ': 'Bộ nhớ',
'U106': 'U106',
'Cổng kết nối': 'Cổng kết nối',
'loại chân cắm': 'Loại chân cắm',
'dung lượng': 'Dung lượng',
'Giá đỡ': 'Giá đỡ',
'Combo sạc': 'Combo sạc',
'Cốc sạc': 'Cốc sạc',
'Cốc Sạc': 'Cốc sạc',
'dây cáp': 'Dây cáp',
'Cốc': 'Cốc',
'màu cáp': 'Màu cáp',
'Mô hình (Màu)': 'Mô hình (Màu)',
'Model (Color)': 'Mô hình (Màu)',
'(Mô Hình) Màu': 'Mô hình (Màu)',
'Corol': 'Màu sắc',
'Mô hình': 'Mô hình',
'Màu sắc:': 'Màu sắc:',
'Màu đầu ra': 'Màu đầu ra',
'Type': 'Loại',
'Length': 'Chiều dài',
'Các biến thể': 'Các biến thể',
'Variants': 'Các biến thể',
'Style': 'Kiểu dáng',
'Version': 'Phiên bản',
'style': 'Kiểu dáng',
'Cloor': 'Màu',
'Chiều dài và m': 'Chiều dài và mét',
'Quantity': 'Số lượng',
'Colors': 'Màu sắc',
'Phù hợp cho:': 'Phù hợp cho:',
'Thông gió': 'Thông gió',
'Loại hình': 'Loại hình',
'Variantion': 'Các biến thể',
'variation': 'Các biến thể',
'TYPE': 'Loại',
'Hình thức giao': 'Hình thức giao',
'Lengths': 'Chiều dài',
'Thông tin chi': 'Thông tin chi tiết',
'Lưu trữ': 'Lưu trữ',
'Vriation': 'Các biến thể',
'Loại phích cắm': 'Loại phích cắm',
'version': 'Phiên bản',
'Be applicable': 'Phù hợp',
'Color Name': 'Tên màu',
'Applicable': 'Phù hợp',
'Body Color': 'Màu cơ thể',
'Compatible': 'Tương thích',
'colour': 'Màu sắc',
'Colores': 'Màu sắc',
'Màu cơ thể': 'Màu cơ thể',
'Types of': 'Các loại',
'None': 'Không',
'Types Of': 'Các loại',
'Lưa chọn': 'Lựa chọn',
'Chuẩn cắm': 'Chuẩn cắm',
'nokia 215': 'Nokia 215',
'Dòng điện thại': 'Dòng điện thoại',
'Dòng iphone': 'Dòng iPhone',
'Màu sạc': 'Màu sạc',
'PRIVACY IP14': 'PRIVACY IP14',
'GLASS+ IP14': 'GLASS+ IP14',
'Dòng iPad': 'Dòng iPad',
'Dòng iPhone': 'Dòng iPhone',
'Model iPhone': 'Model iPhone',
'100w 1m': '100W 1m',
'GLASSXTR2 IP14': 'GLASSXTR2 IP14',
'100w 2m': '100W 2m',
'Tên dòng máy': 'Tên dòng máy',
'100w 3m': '100W 3m',
'Khu vực': 'Khu vực',
'Loại Camera': 'Loại Camera',
'Số thiết bị': 'Số thiết bị',
'Màu sản phẩm': 'Màu sản phẩm',
'CHIỀU DÀI': 'Chiều dài',
'chiều dàu': 'Chiều dài',
'kích thước': 'Kích thước',
'Màu /chân cắm': 'Màu / Chân cắm',
'màu': 'Màu',
'compact _đen': 'Compact - Đen',
'Màu': 'Màu',
'Phong cách': 'Phong cách',
'Tốc độ': 'Tốc độ',
'QCY T1C': 'QCY T1C',
'QCY H2': 'QCY H2',
'Độ dài-màu': 'Độ dài - Màu',
'Màu - độ dài': 'Màu - Độ dài',
'Màu - Dài': 'Màu - Dài',
'Độ dài-Màu': 'Độ dài - Màu',
'Dạng cáp-Dài': 'Dạng cáp - Dài',
'số lượng': 'Số lượng',
'Màu - Độ dài': 'Màu - Độ dài',
'Màu đen': 'Màu đen',
'Loại - KT': 'Loại - Kích thước',
'Kích thước (Dài x Rộng x Cao)': 'Kích thước (Dài x Rộng x Cao)',
'Hình thức dùng': 'Hình thức dùng',
'Size': 'Kích thước',
'Tương thích với': 'Tương thích với',
'Hãng Sản xuất': 'Hãng Sản xuất',
'Giá tiền': 'Giá tiền',
'Dạng dài': 'Dạng dài',
'Nhiệt độ': 'Nhiệt độ',
'Loại': 'Loại',
'dài': 'Dài',
'Nhóm loại': 'Nhóm loại',
'Phong cách dây': 'Phong cách dây',
'Dung lượng (mAh)': 'Dung lượng (mAh)',
'Dài cáp': 'Dài cáp',
'Model-Color': 'Mô hình - Màu sắc',
'màu dây': 'Màu dây',
'Màu-Dài-Cáp': 'Màu - Dài - Cáp',
'Loại dây': 'Loại dây',
'Color-Dài': 'Màu - Dài',
'Thương hiệu': 'Thương hiệu',
'Loại dùng': 'Loại dùng',
'Type Length': 'Loại - Chiều dài',
'loại cáp': 'Loại cáp',
'Loại-Dài': 'Loại - Dài',
'Chức năng sạc': 'Chức năng sạc',
'Điện áp sạc': 'Điện áp sạc',
'Loại cáp sạc': 'Loại cáp sạc',
'loại cáp sạc': 'Loại cáp sạc',
'Chiều dài - Màu': 'Chiều dài - Màu',
'Màu sắc - chiều dài': 'Màu sắc - Chiều dài',
'Loại dây-Dài': 'Loại dây - Dài',
'Kích thước điện thoại': 'Kích thước điện thoại',
'KT màn hình (inch)': 'Kích thước màn hình (inch)',
'KT màn hình (cm)': 'Kích thước màn hình (cm)',
'Loại- Độ dài': 'Loại - Độ dài',
'Type - Length': 'Loại - Chiều dài',
'Kích thước (Dài x Rộng x Cao) mm': 'Kích thước (Dài x Rộng x Cao) mm',
'Chân Sạc': 'Chân sạc',
'Dung lượng pin': 'Dung lượng pin',
'Chọn loại': 'Chọn loại',
'Kích thước màn hình (cm)': 'Kích thước màn hình (cm)',
'Dòng máy tính': 'Dòng máy tính',
'Dung lượng sạc': 'Dung lượng sạc',
'Chiều dài-Loại cáp': 'Chiều dài - Loại cáp',
'Màu - Loại': 'Màu - Loại',
'Type - Color': 'Loại - Màu',
'Thông số kỹ thuật': 'Thông số kỹ thuật',
'Chiều dài cáp': 'Chiều dài cáp',
'màu loại': 'Màu - Loại',
'Kiểu': 'Kiểu',
'Kích thước màn hình': 'Kích thước màn hình',
'Chiều dài cáp (cm)': 'Chiều dài cáp (cm)',
'Công suất': 'Công suất',
'Model - Color': 'Mô hình - Màu',
'Kích thước (D x R x C)': 'Kích thước (Dài x Rộng x Cao)',
'Màu loại': 'Màu - Loại',
'Loại sản phẩm': 'Loại sản phẩm',
'Loại kết nối': 'Loại kết nối',
'Màu-Loại': 'Màu - Loại',
'Loại - Chất liệu': 'Loại - Chất liệu',
'Loại điện thoại': 'Loại điện thoại',
'Dung lượng (mAh)': 'Dung lượng (mAh)',
'Chất liệu': 'Chất liệu',
'Loại - Chất Liệu': 'Loại - Chất liệu',
'Màu sắc (màu)': 'Màu sắc',
'Bộ sản phẩm bao gồm': 'Bộ sản phẩm bao gồm',
'Kiểu kết nối': 'Kiểu kết nối',
'Loại đầu': 'Loại đầu',
'Kích thước (rộng x cao)': 'Kích thước (Rộng x Cao)',
'Màu sắc/Loại': 'Màu sắc/Loại',
'Size (L x W x H) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Type & Length': 'Loại & Chiều dài',
'Type-Length': 'Loại - Chiều dài',
'Kích thước (R x C)': 'Kích thước (Rộng x Cao)',
'Loại cáp (Type)': 'Loại cáp',
'Dung Lượng Pin': 'Dung lượng pin',
'Kích thước (D x R x C)': 'Kích thước (Dài x Rộng x Cao)',
'Màu - Loại': 'Màu - Loại',
'Chiều dài - Loại': 'Chiều dài - Loại',
'Màu loại': 'Màu - Loại',
'Kích thước (r x c)': 'Kích thước (Rộng x Cao)',
'Model-Color': 'Mô hình - Màu',
'Kích thước (d x r x c)': 'Kích thước (Dài x Rộng x Cao)',
'Loại/Chất liệu': 'Loại/Chất liệu',
'Màu - Kích thước': 'Màu - Kích thước',
'Màu / Độ dài': 'Màu - Độ dài',
'Màu-Loại': 'Màu - Loại',
'Size (cm)': 'Kích thước (cm)',
'Type - Color': 'Loại - Màu',
'Loại cáp - Dài': 'Loại cáp - Dài',
'Loại-Dài': 'Loại - Dài',
'Kích thước (rộng x cao) mm': 'Kích thước (Rộng x Cao) mm',
'Kích thước màn hình (rộng x cao)': 'Kích thước màn hình (Rộng x Cao)',
'Kích thước (R x C)': 'Kích thước (Rộng x Cao)',
'Loại cáp - Chiều dài': 'Loại cáp - Chiều dài',
'Màu / Chiều dài': 'Màu - Chiều dài',
'Màu - Độ dài': 'Màu - Độ dài',
'Type-Length': 'Loại - Chiều dài',
'Dung lượng': 'Dung lượng',
'Kích thước (D x R x C) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Loại - Chiều dài': 'Loại - Chiều dài',
'Dòng máy': 'Dòng máy',
'Màu - Dài': 'Màu - Dài',
'Size (L x W x H) mm': 'Kích thước (Dài x Rộng x Cao) mm',
'Màu sắc - Chiều dài': 'Màu sắc - Chiều dài',
'Màu-Dài-Cáp': 'Màu - Dài - Cáp',
'Loại cáp - Độ dài': 'Loại cáp - Độ dài',
'Kích thước (D x R x C) mm': 'Kích thước (Dài x Rộng x Cao) mm',
'Chất Liệu': 'Chất liệu',
'Loại-Dài-Cáp': 'Loại - Dài - Cáp',
'Loại cáp - Độ dài': 'Loại cáp - Độ dài',
'Chiều dài - Màu': 'Chiều dài - Màu',
'Màu - Chiều dài': 'Màu - Chiều dài',
'Loại - Kích thước': 'Loại - Kích thước',
'Màu / Chân cắm': 'Màu / Chân cắm',
'Kích thước (dài x rộng)': 'Kích thước (Dài x Rộng)',
'Màu/Độ dài': 'Màu - Độ dài',
'Loại - Độ dài': 'Loại - Độ dài',
'Màu sắc - Loại': 'Màu - Loại',
'Màu / Loại': 'Màu - Loại',
'Dài (cm)': 'Dài (cm)',
'Kích thước (d x r x c)': 'Kích thước (Dài x Rộng x Cao)',
'Kích thước (dài x rộng x cao)': 'Kích thước (Dài x Rộng x Cao)',
'Size (L x W x H) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Màu sắc (màu)': 'Màu sắc',
'Loại cáp sạc': 'Loại cáp sạc',
'Loại cáp - Dài': 'Loại cáp - Dài',
'Color - Length': 'Màu - Độ dài',
'Loại cáp - Chiều dài': 'Loại cáp - Chiều dài',
'Dung lượng pin': 'Dung lượng pin',
'Loại - Chất liệu': 'Loại - Chất liệu',
'Kích thước (Rộng x Cao)': 'Kích thước (Rộng x Cao)',
'Chân sạc': 'Chân sạc',
'Màu sắc - Loại': 'Màu - Loại',
'Chiều dài - Loại cáp': 'Chiều dài - Loại cáp',
'Loại - Dài': 'Loại - Dài',
'Kích thước (D x R x C) mm': 'Kích thước (Dài x Rộng x Cao) mm',
'Màu - Chiều dài': 'Màu - Chiều dài',
'Loại - Chiều dài': 'Loại - Chiều dài',
'Loại - Màu': 'Loại - Màu',
'Kích thước (D x R x C) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Chất liệu': 'Chất liệu',
'Màu - Loại cáp': 'Màu - Loại cáp',
'Loại - Chất Liệu': 'Loại - Chất liệu',
'Kích thước (dài x rộng)': 'Kích thước (Dài x Rộng)',
'Màu - Kích thước': 'Màu - Kích thước',
'Loại cáp (Type)': 'Loại cáp',
'Dung lượng (mAh)': 'Dung lượng (mAh)',
'Màu - Độ dài': 'Màu - Độ dài',
'Chiều dài cáp (cm)': 'Chiều dài cáp (cm)',
'Kích thước (R x C)': 'Kích thước (Rộng x Cao)',
'Type - Length': 'Loại - Độ dài',
'Loại - Độ dài': 'Loại - Độ dài',
'Kích thước màn hình': 'Kích thước màn hình',
'Kích thước (r x c)': 'Kích thước (Rộng x Cao)',
'Loại cáp (Type)': 'Loại cáp',
'Bộ sản phẩm bao gồm': 'Bộ sản phẩm bao gồm',
'Dòng máy': 'Dòng máy',
'Loại sản phẩm': 'Loại sản phẩm',
'Loại điện thoại': 'Loại điện thoại',
'Kích thước (D x R x C)': 'Kích thước (Dài x Rộng x Cao)',
'Loại kết nối': 'Loại kết nối',
'Kiểu': 'Kiểu',
'Kích thước (rộng x cao)': 'Kích thước (Rộng x Cao)',
'Màu sắc/Loại': 'Màu sắc/Loại',
'Dung lượng (mAh)': 'Dung lượng (mAh)',
'Kích thước (D x R x C)': 'Kích thước (Dài x Rộng x Cao)',
'Dung lượng pin': 'Dung lượng pin',
'Chiều dài cáp': 'Chiều dài cáp',
'Màu loại': 'Màu - Loại',
'Màu-Loại': 'Màu - Loại',
'Kiểu kết nối': 'Kiểu kết nối',
'Loại đầu': 'Loại đầu',
'Size (L x W x H) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Type-Length': 'Loại - Độ dài',
'Kích thước (R x C)': 'Kích thước (Rộng x Cao)',
'Màu sắc (màu)': 'Màu sắc',
'Chiều dài - Loại': 'Chiều dài - Loại',
'Màu loại': 'Màu - Loại',
'Loại cáp (Type)': 'Loại cáp',
'Kích thước (D x R x C) mm': 'Kích thước (Dài x Rộng x Cao) mm',
'Màu - Chiều dài': 'Màu - Chiều dài',
'Loại - Chiều dài': 'Loại - Chiều dài',
'Loại - Màu': 'Loại - Màu',
'Kích thước (D x R x C) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Chất liệu': 'Chất liệu',
'Màu - Loại cáp': 'Màu - Loại cáp',
'Loại - Chất Liệu': 'Loại - Chất liệu',
'Kích thước (dài x rộng)': 'Kích thước (Dài x Rộng)',
'Màu - Kích thước': 'Màu - Kích thước',
'Loại cáp (Type)': 'Loại cáp',
'Dung lượng (mAh)': 'Dung lượng (mAh)',
'Màu - Độ dài': 'Màu - Độ dài',
'Chiều dài cáp (cm)': 'Chiều dài cáp (cm)',
'Kích thước (R x C)': 'Kích thước (Rộng x Cao)',
'Type - Length': 'Loại - Độ dài',
'Loại - Độ dài': 'Loại - Độ dài',
'Kích thước màn hình': 'Kích thước màn hình',
'Kích thước (r x c)': 'Kích thước (Rộng x Cao)',
'Loại cáp (Type)': 'Loại cáp',
'Bộ sản phẩm bao gồm': 'Bộ sản phẩm bao gồm',
'Dòng máy': 'Dòng máy',
'Loại sản phẩm': 'Loại sản phẩm',
'Loại điện thoại': 'Loại điện thoại',
'Kích thước (D x R x C)': 'Kích thước (Dài x Rộng x Cao)',
'Loại kết nối': 'Loại kết nối',
'Kiểu': 'Kiểu',
'Kích thước (rộng x cao)': 'Kích thước (Rộng x Cao)',
'Màu sắc/Loại': 'Màu sắc/Loại',
'Dung lượng (mAh)': 'Dung lượng (mAh)',
'Kích thước (D x R x C)': 'Kích thước (Dài x Rộng x Cao)',
'Dung lượng pin': 'Dung lượng pin',
'Chiều dài cáp': 'Chiều dài cáp',
'Màu loại': 'Màu - Loại',
'Màu-Loại': 'Màu - Loại',
'Kiểu kết nối': 'Kiểu kết nối',
'Loại đầu': 'Loại đầu',
'Size (L x W x H) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Type-Length': 'Loại - Độ dài',
'Kích thước (R x C)': 'Kích thước (Rộng x Cao)',
'Màu sắc (màu)': 'Màu sắc',
'Chiều dài - Loại': 'Chiều dài - Loại',
'Màu loại': 'Màu - Loại',
'Loại cáp (Type)': 'Loại cáp',
'Kích thước (D x R x C) mm': 'Kích thước (Dài x Rộng x Cao) mm',
'Màu - Chiều dài': 'Màu - Chiều dài',
'Loại - Chiều dài': 'Loại - Chiều dài',
'Loại - Màu': 'Loại - Màu',
'Kích thước (D x R x C) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Chất liệu': 'Chất liệu',
'Màu - Loại cáp': 'Màu - Loại cáp',
'Loại - Chất Liệu': 'Loại - Chất liệu',
'Kích thước (dài x rộng)': 'Kích thước (Dài x Rộng)',
'Màu - Kích thước': 'Màu - Kích thước',
'Loại cáp (Type)': 'Loại cáp',
'Dung lượng (mAh)': 'Dung lượng (mAh)',
'Màu - Độ dài': 'Màu - Độ dài',
'Chiều dài cáp (cm)': 'Chiều dài cáp (cm)',
'Kích thước (R x C)': 'Kích thước (Rộng x Cao)',
'Type - Length': 'Loại - Độ dài',
'Loại - Độ dài': 'Loại - Độ dài',
'Kích thước màn hình': 'Kích thước màn hình',
'Kích thước (r x c)': 'Kích thước (Rộng x Cao)',
'Loại cáp (Type)': 'Loại cáp',
'Bộ sản phẩm bao gồm': 'Bộ sản phẩm bao gồm',
'Dòng máy': 'Dòng máy',
'Loại sản phẩm': 'Loại sản phẩm',
'Loại điện thoại': 'Loại điện thoại',
'Kích thước (D x R x C)': 'Kích thước (Dài x Rộng x Cao)',
'Loại kết nối': 'Loại kết nối',
'Kiểu': 'Kiểu',
'Kích thước (rộng x cao)': 'Kích thước (Rộng x Cao)',
'Màu sắc/Loại': 'Màu sắc/Loại',
'Dung lượng (mAh)': 'Dung lượng (mAh)',
'Kích thước (D x R x C)': 'Kích thước (Dài x Rộng x Cao)',
'Dung lượng pin': 'Dung lượng pin',
'Chiều dài cáp': 'Chiều dài cáp',
'Màu loại': 'Màu - Loại',
'Màu-Loại': 'Màu - Loại',
'Kiểu kết nối': 'Kiểu kết nối',
'Loại đầu': 'Loại đầu',
'Size (L x W x H) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Type-Length': 'Loại - Độ dài',
'Kích thước (R x C)': 'Kích thước (Rộng x Cao)',
'Màu sắc (màu)': 'Màu sắc',
'Chiều dài - Loại': 'Chiều dài - Loại',
'Màu loại': 'Màu - Loại',
'Loại cáp (Type)': 'Loại cáp',
'Kích thước (D x R x C) mm': 'Kích thước (Dài x Rộng x Cao) mm',
'Màu - Chiều dài': 'Màu - Chiều dài',
'Loại - Chiều dài': 'Loại - Chiều dài',
'Loại - Màu': 'Loại - Màu',
'Kích thước (D x R x C) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Chất liệu': 'Chất liệu',
'Màu - Loại cáp': 'Màu - Loại cáp',
'Loại - Chất Liệu': 'Loại - Chất liệu',
'Kích thước (dài x rộng)': 'Kích thước (Dài x Rộng)',
'Màu - Kích thước': 'Màu - Kích thước',
'Loại cáp (Type)': 'Loại cáp',
'Dung lượng (mAh)': 'Dung lượng (mAh)',
'Màu - Độ dài': 'Màu - Độ dài',
'Chiều dài cáp (cm)': 'Chiều dài cáp (cm)',
'Kích thước (R x C)': 'Kích thước (Rộng x Cao)',
'Type - Length': 'Loại - Độ dài',
'Loại - Độ dài': 'Loại - Độ dài',
'Kích thước màn hình': 'Kích thước màn hình',
'Kích thước (r x c)': 'Kích thước (Rộng x Cao)',
'Loại cáp (Type)': 'Loại cáp',
'Bộ sản phẩm bao gồm': 'Bộ sản phẩm bao gồm',
'Dòng máy': 'Dòng máy',
'Loại sản phẩm': 'Loại sản phẩm',
'Loại điện thoại': 'Loại điện thoại',
'Kích thước (D x R x C)': 'Kích thước (Dài x Rộng x Cao)',
'Loại kết nối': 'Loại kết nối',
'Kiểu': 'Kiểu',
'Kích thước (rộng x cao)': 'Kích thước (Rộng x Cao)',
'Màu sắc/Loại': 'Màu sắc/Loại',
'Dung lượng (mAh)': 'Dung lượng (mAh)',
'Kích thước (D x R x C)': 'Kích thước (Dài x Rộng x Cao)',
'Dung lượng pin': 'Dung lượng pin',
'Chiều dài cáp': 'Chiều dài cáp',
'Màu loại': 'Màu - Loại',
'Màu-Loại': 'Màu - Loại',
'Kiểu kết nối': 'Kiểu kết nối',
'Loại đầu': 'Loại đầu',
'Size (L x W x H) cm': 'Kích thước (Dài x Rộng x Cao) cm',
'Type-Length': 'Loại - Độ dài',
'Kích thước (R x C)': 'Kích thước (Rộng x Cao)',
'Màu sắc (màu)': 'Màu sắc',
'Loại kính': 'Loại kính',
'Chọn cáp': 'Chọn cáp',
'Chọn loại cáp': 'Chọn loại cáp',
'Chọn bộ': 'Chọn bộ',
'颜色': 'Màu sắc',
'Lưu TRỮ': 'Lưu trữ',
'Color+Size': 'Màu sắc + Kích thước',
'Iphone 4 / 4s': 'iPhone 4 / 4s',
'Color Quantity': 'Số lượng màu',
'Styles': 'Phong cách',
'Shape': 'Hình dạng',
'Pattern': 'Mẫu',
'Phích cắm': 'Phích cắm',
'Đèn LED MÀU': 'Đèn LED Màu',
'Kiểu đầu xịt': 'Kiểu đầu xịt',
'Thông Số': 'Thông số',
'ÁNH SÁNG': 'Ánh sáng',
'1 Nhả Kem': '1 Nhấn Kem',
'LOẠI TĂM NƯỚC': 'Loại tăm nước',
'SẠC': 'Sạc',
'Dòng ĐThoại': 'Dòng Điện thoại',
'Dòng AirPods': 'Dòng AirPods',
'Dòng Đthoại': 'Dòng Điện thoại',
'Màu viền': 'Màu viền',
'Dòng ĐT': 'Dòng Điện thoại',
'Kích Cỡ': 'Kích cỡ',
'\x08Dòng ĐThoại': 'Dòng Điện thoại',
'Kolory': 'Màu sắc',
'Điện thoại Mod': 'Máy điện thoại Mod',
'Mẫu điện thoại': 'Kiểu dáng điện thoại',
'Specification': 'Thông số kỹ thuật',
'Kính cường lực': 'Kính cường lực',
'Thông tin chi': 'Thông tin chi tiết',
'Chiều dài & Lo': 'Chiều dài & Loại',
'Mô hình máy tí': 'Mô hình máy tính',
'Length & Type': 'Chiều dài & Loại',
'Phone Model': 'Kiểu dáng điện thoại',
'mode': 'Kiểu dáng',
'Phone model': 'Kiểu dáng điện thoại',
'Length & Color': 'Chiều dài & Màu sắc',
'Dây trơn': 'Dây trơn',
'Cáp 3 đầu': 'Cáp 3 đầu',
'Cáp dù': 'Cáp dù',
'Cu sac': 'Củ sạc',
'TypeC to TypeC': 'TypeC to TypeC',
'cáp dù TypeC': 'Cáp dù TypeC',
'Balo Laptop': 'Balo Laptop',
'Cáp Iphone': 'Cáp iPhone',
'Chiều dài dây': 'Chiều dài cáp',
'Kiểu dánh': 'Kiểu dáng',
'Kiểu dáng': 'Kiểu dáng',
'Cổng cáp': 'Cổng cáp',
'Họa Tiết': 'Họa tiết',
'Công Suất': 'Công suất',
'Đời máy iPhone': 'Đời máy iPhone',
'Vỏ thiết kế': 'Vỏ thiết kế',
'Case Design': 'Thiết kế vỏ',
'Thiết kế Kasus': 'Thiết kế vỏ',
'loại hình': 'Kiểu dáng',
'người mẫu': 'Người mẫu',
'Bộ Củ + Cáp': 'Bộ sạc + Cáp',
'gõ phím': 'Gõ phím',
'Loại iPhone': 'Đời máy iPhone',
'Màn hình': 'Màn hình',
'Loại sạc': 'Loại sạc',
'DÒng máy': 'Dòng máy',
'Loại miếng dán': 'Loại miếng dán',
'Chọn mã': 'Chọn mã',
'Dành cho ip': 'Dành cho iPhone',
'Ốp chống sốc': 'Ốp chống sốc',
'phân loại': 'Phân loại',
'PHÂN LOẠI': 'Phân loại',
'Phân Loại': 'Phân loại',
'Connector': 'Cổng kết nối',
'SAMSUNG GALAXY': 'Samsung Galaxy',
'Loa bluetooth': 'Loa Bluetooth',
'Các dòng': 'Các dòng',
'Số cổng': 'Số cổng',
'Loại sản phẩm': 'Loại sản phẩm',
'Kho số': 'Kho số',
'Ram l Màu': 'RAM và Màu sắc',
'cấu hình': 'Cấu hình',
'Redmagic': 'Redmagic',
'Đầu sạc': 'Đầu sạc',
'Onlycard': 'Onlycard',
'Chọn dòng IP': 'Chọn dòng iPhone',
'Dòng IPhone': 'Dòng iPhone',
'Sticker 1 chạm': 'Sticker 1 chạm',
'Dòng IP': 'Dòng iPhone',
'dòng iPhone': 'Dòng iPhone',
'CHỌN LOẠI SIM': 'Chọn loại SIM',
'CHỌN SỐ ĐẸP': 'Chọn số đẹp',
'Chọn Loại Sim': 'Chọn loại SIM',
'CHỌN LOẠI GÓI': 'Chọn loại gói',
'CHỌN GÓI SMS': 'Chọn gói SMS',
'Dòng IPHONE': 'Dòng iPhone',
'Mẫu Hình': 'Mẫu hình',
'Phân Loai': 'Phân loại',
'Mẫu hình': 'Mẫu hình',
'Bộ Sạc': 'Bộ sạc',
'Sim_Mobi_DATA': 'Sim Mobi DATA',
'combo': 'Combo',
'Sim 4G': 'Sim 4G',
'ED60': 'ED60',
'sim': 'Sim',
'0d_cogoi': '0d_cogoi',
'Loại sim': 'Loại sim',
'loại sim': 'Loại sim',
'Quà tặng': 'Quà tặng',
'Loại cáp sạc': 'Loại cáp sạc',
'Quà tặng': 'Quà tặng',
'Chân Sạc': 'Chân sạc',
'Loại Đồng Hồ': 'Loại đồng hồ',
'MÀu': 'Màu sắc',
'cường lực': 'Cường lực',
'1 Cổng': '1 Cổng',
'loại': 'Loại',
'Loại thẻ': 'Loại thẻ',
'Màu - Size': 'Màu - Kích thước',
'mẫu ốp': 'Mẫu ốp',
'Dòng xe': 'Dòng xe',
'M220': 'M220',
'G203': 'G203',
'G304': 'G304',
'G102 Lightsync': 'G102 Lightsync',
'M650 Medium': 'M650 Medium',
'M350': 'M350',
'B100|M90': 'B100|M90',
'Logitech': 'Logitech',
'M240': 'M240',
'Chuột': 'Chuột',
'K380+M350': 'K380+M350',
'Logitech G435': 'Logitech G435',
'G333': 'G333',
'MK240': 'MK240',
'Mousepad': 'Mousepad',
'MX Master': 'MX Master',
'POP MOUSE': 'POP MOUSE',
'MX Master 3S': 'MX Master 3S',
'MX Anywhere': 'MX Anywhere',
'MK470': 'MK470',
'G335': 'G335',
'G733': 'G733',
'G Pro X': 'G Pro X',
'A10': 'A10',
'k580': 'k580',
'Lift Vertical': 'Lift Vertical',
'Zone Vibe 100': 'Zone Vibe 100',
'K580+M350': 'K580+M350',
'G Pro': 'G Pro',
'Combo POP': 'Combo POP',
'2MK': '2MK',
'K650': 'K650',
'MX Anywhere 3': 'MX Anywhere 3',
'H390': 'H390',
'Deskmat': 'Deskmat',
'G715 TKL': 'G715 TKL',
'Wonderboom 2': 'Wonderboom 2',
'Wonderboom 3': 'Wonderboom 3',
'G913': 'G913',
'G735': 'G735',
'R500': 'R500',
'POP KEYS': 'POP KEYS',
'kích cỡ': 'Kích cỡ',
'MX Keys Mini': 'MX Keys Mini',
'G512GX + G502': 'G512GX + G502',
'G705': 'G705',
'G502 X P;us': 'G502 X Plus',
'Brio_500': 'Brio 500',
'G435&G304': 'G435&G304',
'G535': 'G535',
'G413': 'G413',
'MX Keys+Master': 'MX Keys+Master',
'Gối Cổ': 'Gối Cổ',
    'MX': 'MX',
    'G502 X WL': 'G502 X WL',
    'M187': 'M187',
    'G715&G705': 'G715&G705',
    'C270&H390': 'C270&H390',
    'MX Master 3': 'MX Master 3',
    'K650+M650': 'K650+M650',
    'G435&G203': 'G435&G203',
    'Brio_300': 'Brio_300',
    'K380+Lift': 'K380+Lift',
    'ComboPOP&Desk': 'ComboPOP&Desk',
    'G813': 'G813',
    'Brio300+Zone': 'Brio300+Zone',
    'MX Mechanical': 'MX Mechanical',
    'G502 X': 'G502 X',
    'MK275&C270': 'MK275&C270',
    'Ví Logitech': 'Ví Logitech',
    'Keys Mini+Any3': 'Keys Mini+Any3',
    'Brio+ZoneVibe': 'Brio+ZoneVibe',
    'Combo MX': 'Combo MX',
    'EarPad': 'EarPad',
    'POP&G435': 'POP&G435',
    'TOP PLATE': 'TOP PLATE',
    'KeyCap': 'KeyCap',
    'G912TKL&G502WL': 'G912TKL&G502WL',
    'Combo AURORA': 'Combo AURORA',
    'iPad Pro': 'iPad Pro',
    'K380+Any 3': 'K380+Any 3',
    'Keys Mini+Lift': 'Keys Mini+Lift',
    'ComboTouch': 'ComboTouch',
    'Mousepad Auror': 'Mousepad Auror',
    'mầu': 'Màu',
    'PPF Trong': 'PPF Trong',
    'iphone': 'iPhone',
    'ip': 'IP',
    'PPF Chống Vân': 'PPF Chống Vân',
    'MẦU': 'Màu',
    'nhóm ip': 'nhóm IP',
    'Mầu': 'Màu',
    'nhóm mầu': 'nhóm Màu',
    'nhóm': 'nhóm',
    'Loại hàng': 'Loại hàng',
    'Pin Deji iP6P': 'Pin Deji iP6P',
    'Pin Deji 7P': 'Pin Deji 7P',
    'Pin Deji IpXsM': 'Pin Deji IpXsM',
    'Pin Deji IpX': 'Pin Deji IpX',
    'Cường lực': 'Cường lực',
    'Pin Deji 8P': 'Pin Deji 8P',
    'Pin Deji iP6s': 'Pin Deji iP6s',
    'Pin Deji Ip': 'Pin Deji Ip',
    'Cáp sạc RC-124': 'Cáp sạc RC-124',
    'Pin Deji 6P': 'Pin Deji 6P',
    'Pin Deji iP7': 'Pin Deji iP7',
    'RC160 i/a/m': 'RC160 i/a/m',
    'Pin Deji Ip6': 'Pin Deji Ip6',
    'Pin Deji iP8': 'Pin Deji iP8',
    'PinDeji iP5-5s': 'Pin Deji iP5-5s',
    'RC-179i/a/m': 'RC-179i/a/m',
    'Loại kính CL': 'Loại kính CL',
    'Loại Bộ sạc': 'Loại bộ sạc',
    'REMAX RPP-166': 'REMAX RPP-166',
    'RC-094': 'RC-094',
    'Dung lượng Pin': 'Dung lượng Pin',
    'RC-188': 'RC-188',
    'Combo giá sỉ': 'Combo giá sỉ',
    'REMAX RPP-96': 'REMAX RPP-96',
    'Số lượng node': 'Số lượng node',
    'Số node': 'Số node',
    'Màu mực': 'Màu mực',
    'Phân Loại GB': 'Phân Loại GB',
    'Phân Loaị': 'Phân Loại',
    'hàng': 'hàng',
    'pl': 'pl',
    'chips CPU': 'chips CPU',
    'Ram': 'Ram',
    'Part Number': 'Part Number',
    'phan loai': 'Phân loại',
    'DÒNG': 'Dòng',
'Office': 'Văn phòng',
'Thiết Kế': 'Thiết kế',
'CTL-4100WL': 'CTL-4100WL',
'M100': 'M100',
'N100': 'N100',
'N120': 'N120',
'M300 Silent': 'M300 Silent',
'E28': 'E28',
'M200': 'M200',
'M218': 'M218',
'V600S': 'V600S',
'V600': 'V600',
'M160': 'M160',
'X1800S': 'X1800S',
'SWITCH': 'Switch',
'8000M': '8000M',
'Loại kích cỡ': 'Loại kích cỡ',
'Chuẩn loại': 'Chuẩn loại',
'Chuẩn': 'Chuẩn',
'M10 Plus': 'M10 Plus',
'9300M': '9300M',
'ĐỘI BÓNG': 'Đội bóng',
'X120 Pro': 'X120 Pro',
'M650': 'M650',
'VT200': 'VT200',
'DPI': 'DPI',
'Máy in nhiệt': 'Máy in nhiệt',
'Loại ổ': 'Loại ổ',
'Phân Loại giấy': 'Phân loại giấy',
'Quà tặng kèm': 'Quà tặng kèm',
'Chuột Gseries': 'Chuột dòng Gseries',
'Phím': 'Bàn phím',
'Mua': 'Mua',
'Volume': 'Âm lượng',
'Tapo': 'Tapo',
'Màu- Dài': 'Màu - Độ dài',
'Camera': 'Camera',
'Các khoảng trố': 'Các khoảng trống',
'Size S': 'Kích thước S',
'Size M': 'Kích thước M',
'Layout': 'Bố cục',
'Độ dày': 'Độ dày',
'Quốc gia': 'Quốc gia',
'Loại Sp': 'Loại sản phẩm',
'DUng lượng': 'Dung lượng',
'MÀU PHÍM': 'Màu phím',
'AKKO SWITCH': 'Switch AKKO',
'LOẠI CABLE': 'Loại cáp',
'SWICH': 'Switch',
'Usb C HUB': 'Bộ chia USB-C',
'USB Sound Card': 'Card âm thanh USB',
'Code': 'Mã',
'NAME': 'Tên',
'Audio Cable': 'Cáp âm thanh',
'Mét': 'Mét',
'USB C HUB': 'Bộ chia USB-C',
'Colo': 'Màu sắc',
'CPU': 'CPU',
'oem': 'OEM',
'Interface': 'Giao diện',
'Speed': 'Tốc độ',
'Mô HÌNH': 'Mô hình',
'Bluetooth': 'Bluetooth',
'Phù hợp với': 'Phù hợp với',
'lenght': 'Độ dài',
'Port': 'Cổng',
'midel': 'Model',
'Oem': 'OEM',
'Protocol': 'Giao thức',
'Box': 'Hộp',
'Dung lượng SSD': 'Dung lượng ổ cứng SSD',
'Phân loại(RAM)': 'Phân loại (RAM)',
'Phần loại': 'Phân loại',
'Màu Săc': 'Màu sắc',
'Mầu sắc': 'Màu sắc',
'Mầu Sắc': 'Màu sắc',
'Mã Phím': 'Mã phím',
'Loại swith': 'Loại switch',
'Loại switch': 'Loại switch',
'Chất liệu': 'Chất liệu',
'NHÓM MÀU': 'Nhóm màu',
'wifi5': 'Wifi 5',
'Màu sắc / kích': 'Màu sắc / kích thước',
'Người mẫu': 'Người mẫu',
'Model（4K@60Hz）': 'Model (4K@60Hz)',
'Phân loại màu': 'Phân loại màu',
'AKKO CS Switch': 'Switch AKKO CS',
'Combo gaming': 'Combo gaming',
'Variant': 'Biến thể',
'Combo Office': 'Combo văn phòng',
'Ports': 'Cổng',
'Sự chỉ rõ': 'Sự chỉ rõ',
'Chất liệu / mà': 'Chất liệu / màu sắc',
'Model/Interfac': 'Model/Giao diện',
'Mô hình & Chiề': 'Mô hình & Chiều dài',
'Kích thước / M': 'Kích thước / Màu sắc',
'Rate': 'Tốc độ',
'SSD Capacity': 'Dung lượng ổ cứng SSD',
'Standard': 'Chuẩn',
'Mô hình & Màu ': 'Mô hình & Màu sắc',
'Màu sắc / Mô h': 'Màu sắc / Mô hình',
'Kích thước và ': 'Kích thước và',
'Mô hình / Màu': 'Mô hình / Màu sắc',
'Mẫu mã & Màu s': 'Mẫu mã & Màu sắc',
'Interfac/Model': 'Giao diện/Mô hình',
'Pack': 'Bao bì',
'Cổng': 'Cổng',
'USB3.2 Gen2': 'USB3.2 Gen2',
'10Gbps Hub': 'Hub 10Gbps',
'sự chỉ rõ': 'Sự chỉ rõ',
'Dòng chiều dài': 'Dòng chiều dài',
'Mô hình / Inte': 'Mô hình/Inte',
'Type-C 6Gbps': 'Type-C 6Gbps',
'Màu lưỡi': 'Màu lưỡi',
'Lưỡi màu': 'Lưỡi màu',
'Core': 'Core',
'Bus': 'Bus',
'Bao Bì': 'Bao bì',
'Màu họa tiết': 'Màu họa tiết',
'Dây Sạc Nhanh': 'Dây Sạc Nhanh',
'Khuyến Mãi': 'Khuyến Mãi',
'Kích cỡ': 'Kích cỡ',
'Iphone': 'iPhone',
'Ipad': 'iPad',
'IPAD': 'iPad',
'switch': 'switch',
'Jack kết nối': 'Jack kết nối',
'Mực in Epson': 'Mực in Epson',
'Mực in T664': 'Mực in T664',
'Mực Epson 005': 'Mực Epson 005',
'C13T06G': 'C13T06G',
'EX200': 'EX200',
'A3002RU-V2': 'A3002RU-V2',
'T6': 'T6',
'X18': 'X18',
'Không ổ cứng': 'Không ổ cứng',
'Trắng': 'Trắng',
'Con số': 'Con số',
'Pocket2': 'Pocket2',
'RSC 2': 'RSC 2',
'RS2': 'RS2',
'Model bản màu': 'Model bản màu',
'Tên mã': 'Tên mã',
'M221 Màu': 'M221 Màu',
'Dành cho máy': 'Dành cho máy',
'M185 MÀU': 'M185 MÀU',
'BẢN': 'Bản',
'Lõi Lọc Cho': 'Lõi Lọc Cho',
'J30E Màu sắc': 'J30E Màu sắc',
'K580 Màu': 'K580 Màu',
'Master 3S Màu': 'Master 3S Màu',
'MX keys Màu': 'MX keys Màu',
'Anywhere 3SMÀU': 'Anywhere 3S Màu',
'NB G40 Màu': 'NB G40 Màu',
'Khăn lau': 'Khăn lau',
'Mã Màu sắc': 'Mã Màu sắc',
'BLACK': 'Đen',
'Anywhere 3 Màu': 'Anywhere 3 Màu',
'Mouse pad': 'Mouse pad',
'Màu sắc K480': 'Màu sắc K480',
'K650 MÀU': 'K650 MÀU',
'Loại cảm biến': 'Loại cảm biến',
'NB-F120': 'NB-F120',
'phiên bản': 'Phiên bản',
'Master 3 For': 'Master 3 For',
'Kèm thẻ nhớ': 'Kèm thẻ nhớ',
'Bản': 'Bản',
'Phiên Bản MX': 'Phiên Bản MX',
'Deco M5': 'Deco M5',
'Phiên bản cho': 'Phiên bản cho',
'Màu Sắc MK470': 'Màu Sắc MK470',
'Tivi Xiaomi A2': 'Tivi Xiaomi A2',
'MUA KÈM': 'MUA KÈM',
'VIETMAP HUD': 'VIETMAP HUD',
'C9 Tùy chọn': 'C9 Tùy chọn',
'Phiên bản màu': 'Phiên bản màu',
'4000D Airflow': '4000D Airflow',
'Gạt Tàn': 'Gạt tàn',
'padabanic A8': 'padabanic A8',
'N6': 'N6',
'9687': '9687',
'Padabanic2218': 'Padabanic2218',
'May Say': 'Máy sấy',
'Padabanic B133': 'Padabanic B133',
'B135': 'B135',
'XỊT DẦU': 'Xịt dầu',
'PD8889': 'PD8889',
'Cân nặng': 'Cân nặng',
'Mẫu nồi': 'Mẫu nồi',
'Màu chổi': 'Màu chổi',
'Bộ điều khiển': 'Bộ điều khiển',
'Kích thước van': 'Kích thước van',
'Van điện từ 34': 'Van điện từ 34',
'Van điện từ 27': 'Van điện từ 27',
'Tủ điều khiển': 'Tủ điều khiển',
'Bộ đóng ngắt': 'Bộ đóng ngắt',
'CTAP': 'CTAP',
'CTDC': 'CTDC',
'Tủ LZ2+': 'Tủ LZ2+',
'Van điện từ 42': 'Van điện từ 42',
'Tủ LZ3': 'Tủ LZ3',
'Massage đầu': 'Massage đầu',
'Van điện từ': 'Van điện từ',
'Van điện từ 49': 'Van điện từ 49',
'Van điện từ 60': 'Van điện từ 60',
'Xịt phòng': 'Xịt phòng',
'Vị': 'Vị',
'Perfect': 'Perfect',
'Kem đánh răng': 'Kem đánh răng',
'f65i': 'f65i',
'Bản màu': 'Bản màu',
'Loại Quạt': 'Loại quạt',
'3 Màu Ánh Sáng': '3 Màu ánh sáng',
'Thương hiệu': 'Thương hiệu',
'BH Toàn Quốc': 'Bảo hành toàn quốc',
'Chính hãng': 'Chính hãng',
'BH 24 Tháng': 'Bảo hành 24 tháng',
'BH 12 tháng': 'Bảo hành 12 tháng',
'BH 12 Tháng': 'Bảo hành 12 tháng',
'Số lưỡi dao': 'Số lưỡi dao',
'Dung tích cối': 'Dung tích cối',
'BH 12 THÁNG': 'Bảo hành 12 tháng',
'BH 24 tháng': 'Bảo hành 24 tháng',
'ADVINDEQ': 'ADVINDEQ',
'Bh Toàn Quốc': 'Bảo hành toàn quốc',
'BH 5 năm': 'Bảo hành 5 năm',
'FujiE': 'FujiE',
'Bh 12 Tháng': 'Bảo hành 12 tháng',
'Bh 24 Tháng': 'Bảo hành 24 tháng',
'HỌA TIẾT': 'Họa tiết',
'KS-COM100DV': 'KS-COM100DV',
'MẦU SẮC': 'Màu sắc',
'MODLE': 'Kiểu mẫu',
'Bình thủy điện': 'Bình thủy điện',
'Máy sấy tóc': 'Máy sấy tóc',
'Panasonic': 'Panasonic',
'QUẠT TREO': 'Quạt treo',
'màng lọc': 'Màng lọc',
'F-PXM35A-B': 'F-PXM35A-B',
'MÃ SẢN PHẨM': 'Mã sản phẩm',
'Bao Gồm': 'Bao gồm',
'Bộ Full': 'Bộ đầy đủ',
'Lưỡi dao': 'Lưỡi dao',
'Độ dài-màu sắc': 'Độ dài - Màu sắc',
'loa bluetooth': 'Loa Bluetooth',
'GIÁ ĐỠ': 'Giá đỡ',
'SEKA': 'SEKA',
'Máy chiếu': 'Máy chiếu',
'Nhóm': 'Nhóm',
'Massage Cổ': 'Massage cổ',
'Súng Massage': 'Súng massage',
'Loại tai nghe': 'Loại tai nghe',
'Massage Tay': 'Massage tay',
'Massage Mắt': 'Massage mắt',
'Phân lọai': 'Phân loại',
'Massage Lưng': 'Massage lưng',
'một sản phẩm': 'Một sản phẩm',
'1 bộ 50 túi': '1 bộ 50 túi',
'1 sản phẩm': 'Một sản phẩm',
'Lựa chon': 'Lựa chọn',
'Massage cổ': 'Massage cổ',
'Massage Da Đầu': 'Massage da đầu',
'Massage tay': 'Massage tay',
'Cân điện tử': 'Cân điện tử',
'dòng sản phẩm': 'Dòng sản phẩm',
'Bếp từ đơn': 'Bếp từ đơn',
'Massage Chân': 'Massage chân',
'Massage Đầu': 'Massage đầu',
'Lựa Chọn': 'Lựa chọn',
'KGRP88': 'KGRP88',
'KGMC09': 'KGMC09',
'bộ thô smax': 'Bộ thô smax',
'MAYXAY': 'Máy xay',
'Màu mặt số' :'Màu sắc',
'Mặt số màu': 'Màu sắc',
'Có 2 màu': 'Màu sắc',
'sp' : 'Sản phẩm',
'SP': 'Sản phẩm',
'Sp': 'Sản phẩm',
'Màu sắc / Màu': 'Màu sắc',
'Size': 'Kích thước'

    }
    return transformation_dict.get(value, value)

# Áp dụng hàm biến đổi vào cột "name_variation"
df_product['name_tier_variation'] = df_product['name_tier_variation'].apply(transform_name_variation)

# Hiển thị dataframe kết quả
print(df_product['name_tier_variation'])

df_product['deep_start_time'] = pd.to_datetime(df_product['deep_start_time'], unit='s')
df_product['deep_end_time'] = pd.to_datetime(df_product['deep_end_time'], unit='s')
df_product['deep_start_date'] = df_product['ctime'].dt.date
df_product['deep_start_time'] = df_product['ctime'].dt.time
df_product['deep_end_date'] = df_product['ctime'].dt.date
df_product['deep_end_time'] = df_product['ctime'].dt.time

#Thay thế giá trị bị missing bằng 0, bằng nội suy, bằng tên hợp lệ
df_product['exclusive_label'] = df_product['exclusive_label'].fillna(0)
df_product['brand'] = df_product['brand'].replace('None', np.nan)
df_product['exclusive_model_ep_discount'] = df_product['exclusive_model_ep_discount'].fillna(0)
df_product['exclusive_model_ep_price'] = df_product['exclusive_model_ep_price'].fillna(0)
df_product['exclusive_url_text'] = df_product['exclusive_url_text'].fillna(0)
df_product['exclusive_url'] = df_product['exclusive_url'].fillna(0)
df_product['exclusive_price_promotion_id'] = df_product['exclusive_price_promotion_id'].fillna(0)
df_product['exclusive_save_amount'] = df_product['exclusive_save_amount'].fillna(0)
df_product['hidden_promotion_price'] = df_product['hidden_promotion_price'].fillna(0)
df_product['deep_promotion_price'] = df_product['deep_promotion_price'].fillna(0)
df_product['deep_start_time'] = df_product['deep_start_time'].fillna(0)
df_product['deep_end_time'] = df_product['deep_end_time'].fillna(0)
df_product['add_on_deal_id'] = df_product['add_on_deal_id'].fillna(0)
df_product['add_on_deal_label'] = df_product['add_on_deal_label'].fillna(0)
df_product['bundle_deal_label'] = df_product['bundle_deal_label'].fillna(0)
df_product['discount_condition_code'] = df_product['discount_condition_code'].fillna(0)
df_product['voucher_code'] = df_product['voucher_code'].fillna(0)
df_product['voucher_id'] = df_product['voucher_id'].fillna(0)
df_product['name_tier_variation'] = df_product['name_tier_variation'].fillna('Không có biến thể')
df_product['option_variation'] = df_product['option_variation'].fillna('Không có biến thể')
df_product['brand'].replace('NoBrand', 'No Brand', inplace=True)

#Xóa dấu cách đầu và cuối, xóa dấu,
df_product = df_product.applymap(lambda x: x.strip() if isinstance(x, str) else x)
df_product.replace(-1, 0, inplace=True)
df_product = df_product.replace({r'\[|\]|\'|\"': ''}, regex=True)

#Phải chuyển đổi sang NaN
df_product['brand'] = df_product['brand'].replace('nan', np.nan)
df_product['option_variation'] = df_product['option_variation'].replace('', np.nan)
df_product['name_tier_variation'] = df_product['name_tier_variation'].replace('', np.nan)

df_product.at[0, 'brand'] = 'Samsung'
df_product.at[56961, 'brand'] = 'LCB'
df_product['brand'].fillna(method='bfill', inplace=True)

df_product.at[56961, 'name_tier_variation'] = 'Không có biến thể'
df_product.at[56961, 'option_variation'] = 'Không có biến thể'

df_product['brand'].unique()

df_product['brand'].fillna(method='bfill', inplace=True)
df_product['option_variation'].fillna(method='bfill', inplace=True)
df_product['name_tier_variation'].fillna(method='bfill', inplace=True)

df_product['option_variation'] = df_product['option_variation'].where(df_product['option_variation'] != 'O', 'Không có biến thể')
df_product['name_tier_variation'] = df_product['name_tier_variation'].where(df_product['name_tier_variation'] != 'O', 'Không có biến thể')

brand_mapping = {
    'Samsung': 'Samsung',
    'Apple': 'Apple',
    'TCL': 'TCL',
    'JBL': 'JBL',
    'harman/kardon': 'Harman/Kardon',
    'Coocaa': 'Coocaa',
    'LG': 'LG',
    'Cuckoo': 'Cuckoo',
    'PHILIPS': 'Philips',
    'Philips': 'Philips',
    'Amazfit': 'Amazfit',
    'soundMAX': 'Soundmax',
    'Soundmax': 'Soundmax',
    'SOUNDMAX': 'Soundmax',
    'Sony': 'Sony',
    'SONY': 'Sony',
    'Jabra': 'Jabra',
    'JaBra': 'Jabra',
    'Bluestone': 'Bluestone',
    'BLUESTONE': 'Bluestone',
    'Kangaroo': 'Kangaroo',
    'Doss': 'Doss',
    'RAVPower': 'RAVPower',
    'Carez': 'Carez',
    'BlueStone': 'Bluestone',
    'Marshall': 'Marshall',
    'TAOTRONICS': 'Taotronics',
    'GARMIN': 'Garmin',
    'Ravpower': 'RAVPower',
    'Skullcandy': 'Skullcandy',
    'Ecovacs': 'Ecovacs',
    'TRONSMART': 'Tronsmart',
    'Tronsmart': 'Tronsmart',
    'COMET': 'Comet',
    'Comet': 'Comet',
    'Coway': 'Coway',
    'Tefal': 'Tefal',
    'TEFAL': 'Tefal',
    'ROMANSON': 'Romanson',
    'ASIAvina': 'AsiaVina',
    'Ariston': 'Ariston',
    'SUNHOUSE': 'Sunhouse',
    'Sunhouse': 'Sunhouse',
    'BioZone': 'BioZone',
    'HAPPY TIME': 'Happy Time',
    'Happy Time': 'Happy Time',
    'sunhouse': 'Sunhouse',
    'Nagakawa': 'Nagakawa',
    'Apex': 'Apex',
    'APEX': 'Apex',
    'Unilever Pure it': 'Unilever Pureit',
    'Pureit': 'Unilever Pureit',
    'Panasonic': 'Panasonic',
    'Flyco': 'Flyco',
    'Joyoung': 'Joyoung',
    'JOYOUNG': 'Joyoung',
    'SHARP': 'Sharp',
    'Happy time': 'Happy Time',
    'Midea': 'Midea',
    'Sanaky': 'Sanaky',
    'Electrolux': 'Electrolux',
    'Tiross': 'Tiross',
    'Toshiba': 'Toshiba',
    'Benny': 'Benny',
    'Magic Korea': 'Magic Korea',
    'Panworld': 'Panworld',
    'Asanzo': 'Asanzo',
    'Hitachi': 'Hitachi',
    'Whirlpool': 'Whirlpool',
    'Perfect': 'Perfect',
    'Thermos': 'Thermos',
    'Braun': 'Braun',
    'Oral-B': 'Oral-B',
    'SEVERIN': 'Severin',
    'Sharp': 'Sharp',
    'MISHIO': 'Mishio',
    'Iruka': 'Iruka',
    'HITACHI': 'Hitachi',
    'Kuvings': 'Kuvings',
    'Fissler': 'Fissler',
    'Severin': 'Severin',
    'Mishio': 'Mishio',
    'Elmich': 'ELMICH',
    'Kachi': 'Kachi',
    'Shimono': 'Shimono',
    'WHIRLPOOL': 'Whirlpool',
    'Hailo': 'Hailo',
    'wusthof': 'Wusthof',
    'Smart Cook': 'Smart Cook',
    'DeLonghi': 'DeLonghi',
    'Zojirushi': 'Zojirushi',
    'TIGER': 'Tiger',
    'ZAMBOO': 'ZAMBOO',
    'BBCooker': 'BBCooker',
    'Mitsubishi': 'Mitsubishi',
    'DAIKIO': 'DAIKIO',
    'Rapido': 'Rapido',
    'PAN WORLD': 'Panworld',
    'KHALUCK.HOME': 'KHALUCK.HOME',
    'MAGIC': 'MAGIC',
    'Daikiosan': 'Daikiosan',
    'DAIKIN': 'Daikin',
    'Winix': 'Winix',
    'Mitsubishi Electric': 'Mitsubishi Electric',
    'Yoobao': 'Yoobao',
    'Karofi': 'Karofi',
    'Daewoo': 'Daewoo',
    'Oneplus': 'OnePlus',
    'Daelux': 'Daelux',
    'Luminarc': 'Luminarc',
    'SENKO': 'Senko',
    'Bullsone': 'Bullsone',
    'Sonax': 'Sonax',
    'NaMilux': 'NaMilux',
    'fujishi': 'Fujishi',
    'Namilux': 'NaMilux',
    'Kim cương': 'Kim Cương',
    'Bluestar': 'Bluestar',
    'Senko': 'Senko',
    'Fujishi': 'Fujishi',
    'FUJISHI': 'Fujishi',
    'Rinnai': 'Rinnai',
    'Lifan': 'Lifan',
    'Gali': 'Gali',
    'senko': 'Senko',
    'Fujie': 'Fujie',
    'CANZY': 'Canzy',
    'DAEWOO': 'Daewoo',
    'FUJIPAN': 'Fujipan',
    'Kaff': 'Kaff',
    'LIFAN': 'Lifan',
    'ALPHA': 'Alpha',
    'BLUESTAR': 'Bluestar',
    'GIOVANNI': 'Giovanni',
    'Nasonal': 'Nasonal',
    'Sogo': 'Sogo',
    'KAFF': 'Kaff',
    'TIROSS': 'Tiross',
    'SAWANA': 'Sawana',
    'Canzy': 'Canzy',
    'Faster': 'Faster',
    'LiFan': 'Lifan',
    'fujipan': 'Fujipan',
    'BLUE STAR': 'Blue Star',
    'ONE MOM': 'One Mom',
    'KYOFA': 'Kyofa',
    'GreenCook': 'Green Cook',
    'FUJIKA': 'Fujika',
    'OSAKO': 'Osako',
    'Hayasa': 'Hayasa',
    'HAYASA': 'Hayasa',
    'Raiden': 'Raiden',
    'Povena': 'Povena',
    'Osako': 'Osako',
    'MATIKA': 'Matika',
    'Cook-Way': 'Cook-Way',
    'Korihome': 'Korihome',
    'Forseti': 'Forseti',
    'LOCK&LOCK': 'Lock & Lock',
    'ChungHo': 'ChungHo',
    'A. O. Smith': 'A. O. Smith',
    'KDK': 'KDK',
    'Delonghi': 'Delonghi',
    'Lock&lock': 'Lock & Lock',
    'HUROM': 'Hurom',
    'Malloca': 'Malloca',
    'Tiger': 'Tiger',
    'Deton': 'Deton',
    'PERFECT': 'Perfect',
    'Hatachi': 'Hatachi',
    'SOWUN': 'SOWUN',
    'Goldsun': 'Goldsun',
    'Kitchen Flower': 'Kitchen Flower',
    'AQUA': 'Aqua',
    'Dalton': 'Dalton',
    'Homepro': 'Homepro',
    'Yage': 'Yage',
    'Hans': 'Hans',
    'Kohn': 'Kohn',
    'LiOA': 'LiOA',
    'Kottmann': 'Kottmann',
    'SAVTM': 'SAVTM',
    'Greencook': 'Greencook',
    'GREENCOOK': 'Greencook',
    'Heizen': 'Heizen',
    'Green Cook': 'Greencook',
    'COOKIN': 'Cookin',
    'Masuto': 'Masuto',
    'masuto': 'Masuto',
    'brother': 'Brother',
    'Deerma': 'Deerma',
    'Arirang Life': 'Arirang Life',
    'ArirangLIFE': 'Arirang Life',
    'Eufy': 'Eufy',
    'eufy': 'Eufy',
    'comet': 'Comet',
    'AC': 'AC',
    'TiLoKi': 'TiLoKi',
    'Vie': 'Vie',
    'MUTOSI': 'MUTOSI',
    'Mutosi': 'MUTOSI',
    'MOKKOM': 'MOKKOM',
    'whifa': 'Whifa',
    'EARLDOM': 'Earldom',
    'Earldom': 'Earldom',
    'Romanson': 'Romanson',
    'Yeelight': 'Yeelight',
    'MAX AIR': 'MAX AIR',
    'SENNHEISER': 'Sennheiser',
    'ELPA': 'ELPA',
    'KASHIMURA': 'Kashimura',
    'Elecom': 'Elecom',
    'ELECOM': 'Elecom',
    'Kashimura': 'Kashimura',
    'Yamaha': 'Yamaha',
    'hoco.': 'Hoco',
    'GrownTech': 'GrownTech',
    'Daniel Klein': 'Daniel Klein',
    'ROBOT': 'Robot',
    'VIVAN': 'Vivan',
    'ACOME': 'Acome',
    'Acome': 'Acome',
    'DEVIA': 'Devia',
    'elmich': 'Elmich',
    'TP-LINK': 'TP-Link',
    'KAW': 'KAW',
    'AKEI': 'AKEI',
    'KAWAN': 'KAWAN',
    'Xiaomi': 'Xiaomi',
    'Royal Crown': 'Royal Crown',
    'Huawei': 'Huawei',
    'HUAWEI': 'Huawei',
    'Apple.': 'Apple',
    'ANKER': 'Anker',
    'Anker': 'Anker',
    'EUFY': 'Eufy',
    'Soundcore': 'Soundcore',
    'SoundCore': 'Soundcore',
    'OPPO': 'OPPO',
    'Energizer': 'Energizer',
    'MiLi': 'MiLi',
    'Remax': 'Remax',
    'NTC': 'NTC',
    'Kisonli': 'Kisonli',
    'NTComputer': 'NTComputer',
    'FD': 'FD',
    'HP': 'HP',
    'BOSSTON': 'Bosston',
    'Baseus': 'Baseus',
    'SanDisk': 'SanDisk',
    'Borofone': 'Borofone',
    'Romoss': 'Romoss',
    'NETAC': 'NETAC',
    'Sandisk': 'SanDisk',
    'KIOXIA': 'KIOXIA',
    'Hoco.': 'Hoco',
    'R8': 'R8',
    'Lexar': 'Lexar',
    'Kingston': 'Kingston',
    'Tenda': 'Tenda',
    'Hoco': 'Hoco',
    'FreeLook': 'FreeLook',
    'Plantronics': 'Plantronics',
    'adonit': 'Adonit',
    'Ugreen': 'Ugreen',
    'Lenovo': 'Lenovo',
    'TOTOLINK': 'TOTOLINK',
    'ZADEZ': 'ZADEZ',
    'olevs': 'Olevs',
    'RAPOO': 'RAPOO',
    'PISEN': 'Pisen',
    'Pisen': 'Pisen',
    'pisen': 'Pisen',
    'AKG': 'AKG',
    'Benks': 'Benks',
    'TOPK': 'TOPK',
    'Essager': 'Essager',
    'FONKEN': 'Fonken',
    'Fonken': 'Fonken',
    'Gear4': 'Gear4',
    'UAG': 'UAG',
    'QCY': 'QCY',
    'llano': 'Llano',
    'BASEUS': 'Baseus',
    'Nillkin': 'Nillkin',
    'Zadez': 'Zadez',
    'Adonit': 'Adonit',
    'NOKIA': 'Nokia',
    'ROCKSPACE': 'Rockspace',
    'ROCK SPACE': 'Rockspace',
    'rock space': 'Rockspace',
    'Mophie': 'Mophie',
    'InvisibleShield': 'InvisibleShield',
    'ZAGG': 'ZAGG',
    'iFrogz': 'iFrogz',
    'GEAR4': 'Gear4',
    'Vivas': 'Vivas',
    'VNPT': 'VNPT',
    'igate': 'iGate',
    'iGate': 'iGate',
    'iFROGZ': 'iFrogz',
    'CRRJU': 'CRRJU',
    'Vention': 'Vention',
    'Kuulaa': 'Kuulaa',
    'kuulaa': 'Kuulaa',
    'KUULAA': 'Kuulaa',
    'Divoom': 'Divoom',
    'TEAMGROUP': 'Teamgroup',
    'Teamgroup': 'Teamgroup',
    'Dmax': 'Dmax',
    'Team Group': 'Team Group',
    'ADATA': 'ADATA',
    'Silicon Power': 'Silicon Power',
    'Adata': 'Adata',
    'Power Silicon': 'Silicon Power',
    'AKUS': 'AKUS',
    'UGREEN': 'UGREEN',
    'Fengzhi': 'Fengzhi',
    'FengZhi': 'Fengzhi',
    'FengZhiLife': 'Fengzhi',
    'Cheero': 'Cheero',
    'Kivee': 'Kivee',
    'ZMI': 'ZMI',
    'Divi': 'Divi',
    'SGALAS': 'SGALAS',
    'Sgalas': 'SGALAS',
    'Zeelot': 'Zeelot',
    'zeelot': 'Zeelot',
    'logitech': 'Logitech',
    'iWalk': 'iWalk',
    'Aukey': 'Aukey',
    'Vsmart': 'Vsmart',
    'nokia': 'Nokia',
    'Bagi': 'Bagi',
    'SoundPEATS': 'SoundPEATS',
    'Mazer': 'Mazer',
    'SUNTAIHO': 'SUNTAIHO',
    'SOUNDPEATS': 'SoundPEATS',
    'Switcheasy': 'Switcheasy',
    'LAZICO': 'LAZICO',
    'Vivo': 'Vivo',
    'Happy Home Pro': 'Happy Home Pro',
    'JVJ': 'JVJ',
    'Llano': 'Llano',
    'SAMSUNG': 'Samsung',
    'HdoorLink': 'HdoorLink',
    'HDoorLink': 'HdoorLink',
    'Unique Case': 'Unique Case',
    'Unique Case EST.215': 'Unique Case EST.215',
    'Robot Holder': 'Robot Holder',
    'FNGEEN': 'FNGEEN',
    'FOURRON': 'FOURRON',
    'Sido Tech': 'Sido Tech',
    'JURSUE': 'JURSUE',
    'VENTION': 'Vention',
    'vitog': 'Vitog',
    'GUTEK': 'GUTEK',
    'Belkin': 'Belkin',
    'WK': 'WK',
    'HD Design': 'HD Design',
    'CHARLES': 'CHARLES',
    'mobifone': 'Mobifone',
    'Nescafe': 'Nescafe',
    'LOGITECH': 'Logitech',
    'Logitech': 'Logitech',
    'Asus': 'Asus',
    'DEJI': 'DEJI',
    'iSen': 'iSen',
    'Western Digital': 'Western Digital',
    'DELL': 'Dell',
    'Acer': 'Acer',
    'Microsoft': 'Microsoft',
    'Seagate': 'Seagate',
    'LaCie': 'LaCie',
    'Wacom': 'Wacom',
    'WACOM': 'Wacom',
    'Rapoo': 'Rapoo',
    'rapoo': 'Rapoo',
    'steelseries': 'Steelseries',
    'Steelseries': 'Steelseries',
    'TP-LiNK': 'TP-Link',
    'Mercusys': 'Mercusys',
    'TP-Link': 'TP-Link',
    'TP Link': 'TP-Link',
    'Corsair': 'Corsair',
    'CORSAIR': 'Corsair',
    'Fuhlen': 'Fuhlen',
    'SSTC': 'SSTC',
    'Jasoz': 'Jasoz',
    'Intel': 'Intel',
    'FANTECH': 'FANTECH',
    'FILCO': 'FILCO',
    'VERBATIM': 'Verbatim',
    'transcend': 'Transcend',
    'Verbatim': 'Verbatim',
    'SYNOLOGY': 'Synology',
    'Synology': 'Synology',
    'Transcend': 'Transcend',
    'Terramaster': 'Terramaster',
    'Tránend': 'Tránend',
    'BenQ': 'BenQ',
    'XP-Pen': 'XP-Pen',
    'Akko': 'Akko',
    'Batianda': 'Batianda',
    'msi': 'MSI',
    'XGIMI': 'XGIMI',
    'Dell': 'Dell',
    'DAREU': 'DAREU',
    'Glorious': 'Glorious',
    'hp': 'HP',
    'HYPERX': 'HyperX',
    'Orico': 'Orico',
    'ORICO': 'Orico',
    'Lenovo.': 'Lenovo',
    'POPO': 'POPO',
    'Prolink': 'Prolink',
    'prolink': 'Prolink',
    'Newmen': 'Newmen',
    'Zidli': 'Zidli',
    'ZIDLI': 'Zidli',
    'zidli': 'Zidli',
    'EPSON': 'Epson',
    'Canon': 'Canon',
    'FullmarK': 'Fullmark',
    'HIKVISION': 'Hikvision',
    'EZVIZ': 'EZVIZ',
    'North Bayou': 'North Bayou',
    'deerma': 'Deerma',
    'FPT': 'FPT',
    'Qihoo': 'Qihoo',
    'Showsee': 'Showsee',
    'VietMap': 'VietMap',
    'Blurams': 'Blurams',
    'Kioxia': 'Kioxia',
    'Momoda': 'Momoda',
    'APC': 'APC',
    'VIETMAP': 'VietMap',
    'Sjcam': 'Sjcam',
    'NetCAM': 'NetCAM',
    'Selens': 'Selens',
    'Aolikes': 'Aolikes',
    'Daban': 'Daban',
    'Spor': 'Spor',
    'xiaomi': 'Xiaomi',
    'SKMEI': 'SKMEI',
    'Crnaira': 'Crnaira',
    'TISSELLY': 'TISSELLY',
    'SBAO': 'SBAO',
    'CASIO': 'Casio',
    'KINGNUOS': 'KINGNUOS',
    'Olym Pianus': 'Olym Pianus',
    'OLYM PIANUS': 'Olym Pianus',
    'BENTLEY': 'Bentley',
    'SUNRISE': 'SUNRISE',
    'Bentley': 'Bentley',
    'Olympia Star': 'Olympia Star',
    'Xiaoya': 'Xiaoya',
    'XIAOYA': 'Xiaoya',
    'OPK': 'OPK',
    'OLIKA': 'OLIKA',
    'Sanda': 'Sanda',
    'SANDA': 'Sanda',
    'Thép không gỉ': 'Thép không gỉ',
    'SR Watch': 'SR Watch',
    'SRWATCH': 'SR Watch',
    'Seiko': 'Seiko',
    'SEIKO': 'Seiko',
    'JULIUS': 'Julius',
    'Julius': 'Julius',
    'CITIZEN': 'Citizen',
    'mangOsteen': 'mangOsteen',
    'KAMLON': 'KAMLON',
    'Valence': 'Valence',
    'Q&Q': 'Q&Q',
    'Citizen Q&Q': 'Citizen Q&Q',
    'Timex': 'Timex',
    'CURNON': 'CURNON',
    'Curnon': 'CURNON',
    'ICE WATCH': 'ICE WATCH',
    'Fossil': 'Fossil',
    'Michael Kors': 'Michael Kors',
    'Emprio Armani': 'Emporio Armani',
    'BOSTANTEN': 'BOSTANTEN',
    'Bostanten': 'BOSTANTEN',
    'DANIEL KLEIN': 'Daniel Klein',
    'Orient': 'Orient',
    'Hegner': 'Hegner',
    'NIBOSI': 'NIBOSI',
    'Mini Focus': 'Mini Focus',
    'MINI FOCUS': 'Mini Focus',
    'CDE Jewelry': 'CDE Jewelry',
    'FREELOOK': 'FREELOOK',
    'Senaro': 'Senaro',
    'Sunflame': 'Sunflame',
    'SUN FLAME': 'Sunflame',
    'Sun Flame': 'Sunflame',
    'Cardino': 'Cardino',
    'TITAN': 'TITAN',
    'Anne Klein': 'Anne Klein',
    'OBAKU': 'OBAKU',
    'ADRIATICA': 'Adriatica',
    'Just Cavalli': 'Just Cavalli',
    'ROYAL LONDON': 'ROYAL LONDON',
    'Lacoste': 'Lacoste',
    'Adriatica': 'Adriatica',
    'VARADO': 'VARADO',
    'TEINTOP': 'TEINTOP',
    'Teintop': 'TEINTOP',
    'LOBINNI': 'LOBINNI',
    'KASSAW': 'KASSAW',
    'Lobinni': 'Lobinni',
    'Poniger': 'Poniger',
    'HAZEAL': 'HAZEAL',
    'Kassaw': 'KASSAW',
    'Carnival': 'Carnival',
    'carnival': 'Carnival',
    'REEF TIGER': 'REEF TIGER',
    'Ogival': 'Ogival',
    'Reef Tiger': 'REEF TIGER',
    'LIGE': 'LIGE',
    'PAGINI': 'PAGINI',
    'RAM Leather': 'RAM Leather',
    'WWOOR': 'WWOOR',
    'Aries Gold': 'Aries Gold',
    'Jacques Lemans': 'Jacques Lemans',
    'Wwoor': 'WWOOR',
    'Diamond D': 'Diamond D',
    'Atlantic': 'Atlantic',
    'SUNTEK': 'SUNTEK',
    'Suntek': 'SUNTEK',
    'SUNTEK Audio': 'SUNTEK Audio',
    'ARUN': 'ARUN',
    'Arun': 'ARUN',
    'ZENDURE': 'ZENDURE',
    'BOYA': 'BOYA',
    'Việt Star Quốc Tế': 'Việt Star Quốc Tế',
    'VIET STAR QUOC TE': 'Việt Star Quốc Tế',
    'Mobell': 'Mobell',
    'Malata': 'Malata',
    'Motorola': 'Motorola',
    'Vitog': 'Vitog',
    'GOOJODOQ': 'GOOJODOQ',
    'Godox': 'Godox',
    'Sidotech': 'Sidotech',
    'Xiaomi.': 'Xiaomi',
    'Bear': 'Bear',
    'sony': 'Sony',
    'E-DRA': 'E-DRA',
    'Rock': 'Rock',
    'SARAMONIC': 'SARAMONIC',
    'Saramonic': 'SARAMONIC',
    'PLEXTONE': 'PLEXTONE',
    'Plextone': 'PLEXTONE',
    'AWEI': 'AWEI',
    'awei': 'AWEI',
    'AORON': 'AORON',
    'Yoice': 'Yoice',
    'PICOOC': 'PICOOC',
    'CHEF&CHEF': 'CHEF&CHEF',
    'cuckoo': 'cuckoo',
    'PHILLIPS': 'Philips',
    'SmartCook': 'SmartCook',
    'TOSHIBA': 'Toshiba',
    'unie': 'unie',
    'Kalite': 'Kalite',
    'JIASHI': 'JIASHI',
    '3M': '3M',
    'BIYI': 'BIYI',
    'HoMedics': 'HoMedics',
    'Biok': 'Biok',
    'Ami': 'Ami',
    'Nuna': 'Nuna',
    'Catchy cosmetics': 'Catchy cosmetics',
    'CatChy': 'Catchy',
    'Catchy': 'Catchy',
    'dental': 'dental',
    'ASIA LIGHTING': 'ASIA LIGHTING',
    'NIKITO': 'NIKITO',
    'Unilever pure it': 'Unilever Pureit',
    'Galanz': 'Galanz',
    'MITSUBISHI': 'Mitsubishi',
    'KAROFI': 'KAROFI',
    'Olivo': 'Olivo',
    'AOSmith': 'AOSmith',
    'MIXCDER': 'MIXCDER',
    'UNIE': 'UNIE',
    'AVANTREE': 'AVANTREE',
    'Inphic': 'Inphic',
    'INPHIC': 'Inphic',
    'Avantree': 'AVANTREE',
    'lock & lock': 'Lock & Lock',
    'Lock & Lock': 'Lock & Lock',
    'Smart Cook': 'SmartCook',
    'Lock & Lock': 'Lock & Lock'
}

df_product['brand'] = df_product['brand'].map(brand_mapping)

#Xóa dấu cách đầu và cuối
df_product = df_product.applymap(lambda x: x.strip() if isinstance(x, str) else x)

"""**4.1. Rating**"""

import io
df = pd.read_csv('D:\Final project program\Data\shop_products.csv', low_memory=False)

df_product['item_rating'] = df['item_rating']

# Lấy tất cả giá trị của trường "item_rating"
df_product['item_rating'] = df_product['item_rating'].apply(ast.literal_eval)

item_ratings = df_product['item_rating'].tolist()

# Khởi tạo danh sách trống để lưu trữ các giá trị mới
rating_stars = []
rating_counts = []
rcounts_with_context = []
rcounts_with_image = []

# Lặp qua từng giá trị và trích xuất các trường mới
for value in item_ratings:
    rating_star = value.get('rating_star', None)
    rating_count = value.get('rating_count', None)
    rcount_with_context = value.get('rcount_with_context', None)
    rcount_with_image = value.get('rcount_with_image', None)

    rating_stars.append(rating_star)
    rating_counts.append(rating_count)
    rcounts_with_context.append(rcount_with_context)
    rcounts_with_image.append(rcount_with_image)

# Thêm 4 trường mới vào DataFrame df
df_product = df_product.assign(rating_star=rating_stars,
                             rating_count=rating_counts,
                             rcount_with_context=rcounts_with_context,
                             rcount_with_image=rcounts_with_image)

#Tách trường rating_count thành 5 trường:
# Tách trường rating_count thành các cột rating_count, rating_count_1, rating_count_2, rating_count_3, rating_count_4, rating_count_5

df_product['rating_count'] = df_product['rating_count'].apply(lambda x: ', '.join(map(str, x)))
df_product[['rating_count', 'rating_count_1', 'rating_count_2', 'rating_count_3', 'rating_count_4', 'rating_count_5']] = df_product['rating_count'].str.split(', ', expand=True)

def extract_score(row):
    if isinstance(row, str):
        start_index = row.find("SCORE:")
        if start_index != -1:
            start_index += len("SCORE:")
            end_index = row.find("}", start_index)
            score = row[start_index:end_index]
            return score
    return 0

# Áp dụng hàm trên cột 'info' để tạo cột 'score'
df_product['score'] = df_product['info'].apply(extract_score)

df_product['score'] = df_product['score'].astype('float64')

df_product['rating_count_1'] = df_product['rating_count_1'].astype(int)
df_product['rating_count_2'] = df_product['rating_count_2'].astype(int)
df_product['rating_count_3'] = df_product['rating_count_3'].astype(int)
df_product['rating_count_4'] = df_product['rating_count_4'].astype(int)
df_product['rating_count_5'] = df_product['rating_count_5'].astype(int)

"""**4.2 Flash sale**"""

df_product['flash_sale_counts'] = df_product['flash_sale_infos'].apply(lambda x: x.count('start_time') if isinstance(x, str) else 0)

df_product['flash_sale_infos'].fillna('Chưa từng flash sale', inplace=True)

df_product.loc[df_product['flash_sale_infos'] != 'Chưa từng flash sale', 'flash_sale_infos'] = 'Đã từng flash sale'

df_product['shop_location'] = df_product['shop_location'].fillna('Không công khai địa chỉ')

# Điền giá trị vào cột df_product['deep_discount_id']

df_product.at[0, 'brand'] = 'Samsung'

df_product.at[56961, 'brand'] = 'LCB'

df_product['brand'].fillna(method='bfill', inplace=True)

columns_to_fill = ['discount_condition_percentage', 'discount_condition_cash']
df_product[columns_to_fill] = df_product[columns_to_fill].fillna(0)

# Xóa các trường không cần thiết khỏi DataFrame
fields_to_drop = [
    'label_ids', 'image', 'images', 'status', 'liked', 'flag', 'cb_option', 'raw_discount', 'discount',
    'video_info_list', 'item_type', 'item_rating', 'reference_item_id', 'transparent_background_image',
    'badge_icon_type', 'shopee_verified', 'is_official_shop', 'show_official_shop_label', 'show_shopee_verified_label',
    'show_official_shop_label_in_title', 'is_non_cc_installment_payment_eligible', 'welcome_package_type', 'data_type',
    'shop_rating', 'shop_name', 'is_mart', 'size_chart', 'long_images', 'ctime', 'voucher_info', 'add_on_deal_info',
    'bundle_deal_info', 'deep_discount_skin', 'exclusive_price_info', 'info', 'tier_variations',
    'is_preferred_plus_seller', 'name', 'flash_sale_infos', 'is_service_by_shopee', 'catid', 'reference_item_id',
     'size_chart', 'long_images', 'bundle_deal_info', 'transparent_background_image', 'add_on_deal_info',
    'discount', 'add_on_deal_info', 'deep_discount_skin', 'video_info_list', 'price_min_before_discount', 'price_max_before_discount',
    'price_before_discount', 'deep_start_time', 'deep_end_time', 'deep_start_date', 'deep_end_date', 'exclusive_url_text', 'exclusive_url',
    'condition', 'discount_name', 'voucher_label', 'bundle_deal_label'
]

df_product = df_product.drop(fields_to_drop, axis=1)

def missingCounter(df):
    missing_data = df.isna().sum()
    missing_data = missing_data[missing_data > 0].sort_values(ascending=False)
    print(missing_data)

    return missing_data.index
missingFeatures = missingCounter(df_product)

for column, dtype in df_product.dtypes.items():
    print(f"Column: {column}, Data Type: {dtype}")

bool_columns = df_product.select_dtypes(include=['bool']).columns

for column in bool_columns:
    df_product[column] = df_product[column].astype(str)

try:
    # Tạo đối tượng connection
    myconn = mysql.connector.connect(host="localhost", user="root", passwd="Thuy281001", database="shopee_staging2")

    # Tạo đối tượng cursor
    cur = myconn.cursor()

    for index, row in df_product.iterrows():
        query = """
        INSERT INTO product (
            itemid, product_name, product_creation_date, product_creation_time, name_tier_variation,
            option_variation, shopid, currency, stock, sold, historical_sold, shop_location, liked_count,
            brand, item_status, price, price_min, price_max, has_lowest_price_guarantee,
            show_discount, is_adult, is_cc_installment_payment_eligible, show_free_shipping,
            can_use_bundle_deal, can_use_wholesale, has_model_with_available_shopee_stock,
            can_use_cod, voucher_id, voucher_code, voucher_cash_discount, voucher_percentage,
            voucher_coin_refund, add_on_deal_id, add_on_deal_label, bundle_deal_id, buy,
            get_off_cash, get_off_percentage, hidden_promotion_price, deep_promotion_price,
            exclusive_price_promotion_id, exclusive_save_amount, exclusive_label,
            exclusive_model_ep_price, exclusive_model_ep_discount, discount_condition_code,
            discount_condition_percentage, discount_condition_cash, condition_discount,
            cmt_count, rating_star, rating_count, rcount_with_context, rcount_with_image,
            rating_count_1, rating_count_2, rating_count_3, rating_count_4, rating_count_5,
            score, is_on_flash_sale, flash_sale_ongoing_sold_count, flash_sale_stock, flash_sale_counts
        )
        VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s
             
        )
        """
        data = (
            row['itemid'], row['product_name'], row['product_creation_date'], row['product_creation_time'],
            row['name_tier_variation'], row['option_variation'], row['shopid'], row['currency'],
            row['stock'], row['sold'], row['historical_sold'], row['shop_location'], row['liked_count'], row['brand'], row['item_status'],
            row['price'], row['price_min'], row['price_max'], row['has_lowest_price_guarantee'],
            row['show_discount'], row['is_adult'], row['is_cc_installment_payment_eligible'],
            row['show_free_shipping'], row['can_use_bundle_deal'], row['can_use_wholesale'],
            row['has_model_with_available_shopee_stock'], row['can_use_cod'], row['voucher_id'],
            row['voucher_code'], row['voucher_cash_discount'], row['voucher_percentage'], row['voucher_coin_refund'],
            row['add_on_deal_id'], row['add_on_deal_label'], row['bundle_deal_id'], row['buy'],
            row['get_off_cash'], row['get_off_percentage'], row['hidden_promotion_price'],
            row['deep_promotion_price'], row['exclusive_price_promotion_id'], row['exclusive_save_amount'],
            row['exclusive_label'], row['exclusive_model_ep_price'], row['exclusive_model_ep_discount'],
            row['discount_condition_code'], row['discount_condition_percentage'], row['discount_condition_cash'],
            row['condition_discount'], row['cmt_count'], row['rating_star'], row['rating_count'],
            row['rcount_with_context'], row['rcount_with_image'], row['rating_count_1'],
            row['rating_count_2'], row['rating_count_3'], row['rating_count_4'], row['rating_count_5'],
            row['score'], row['is_on_flash_sale'], row['flash_sale_ongoing_sold_count'],
            row['flash_sale_stock'], row['flash_sale_counts']
        )

        cur.execute(query, data)
        myconn.commit()

    print("Data inserted successfully")

except mysql.connector.Error as e:
    print("Error:", e)
    myconn.rollback()

finally:
    # Đóng đối tượng cursor và kết nối
    if myconn.is_connected():
        cur.close()
        myconn.close()
        print("MySQL connection closed")